#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

usage() {
  cat <<'USAGE'
Usage:
  macos-reset-uninstall-operator-intent-contract.sh

Emits the no-effect macOS reset/uninstall operator-intent contract. It defines
the explicit future approval evidence required before a live reset/uninstall
could be considered, but it does not prompt for approval, infer approval, enable
live activity, delete files, write receipts, mutate host state, open the
network, or claim reset/uninstall implementation.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
UNAME_S=$(uname -s 2>/dev/null || printf 'unknown')
UNAME_M=$(uname -m 2>/dev/null || printf 'unknown')

cat <<REPORT
MACOS RESET UNINSTALL OPERATOR INTENT CONTRACT

reset_uninstall_operator_intent_contract_status=ok
macos_reset_uninstall_operator_intent_contract_present=1
macos_reset_uninstall_effect_authorization_contract_present=1
macos_reset_uninstall_evidence_bundle_contract_present=1
macos_reset_uninstall_live_implementation_plan_contract_present=1
macos_reset_uninstall_live_execution_preflight_contract_present=1
macos_reset_uninstall_live_denial_transcript_contract_present=1
live_execution_preflight_contract_state=closed-no-effect
live_execution_preflight_passed=0
live_execution_preflight_blocking=1
live_execution_preflight_deletion_enabled=0
live_denial_transcript_contract_state=recorded-no-effect
live_denial_transcript_recorded=1
live_denial_transcript_stdout_only=1
live_denial_transcript_file_write_enabled=0
live_implementation_plan_contract_state=defined-no-effect
live_reset_uninstall_implementation_present=0
evidence_bundle_contract_state=defined-no-effect
evidence_bundle_complete=0
effect_authorization_contract_state=closed-no-effect
effect_authorization_open=0
reset_uninstall_effect_authorized=0
repo_root=$ROOT
host_kernel_name=$UNAME_S
host_arch=$UNAME_M
operator_intent_contract_state=defined-no-effect
operator_intent_contract_decision=contract-defined-intent-not-observed
operator_intent_contract_required=1
operator_intent_contract_open=0
operator_reset_uninstall_intent_required=1
operator_reset_uninstall_intent_evidence_required=1
operator_reset_uninstall_intent_evidence_present=0
operator_explicit_reset_uninstall_intent_observed=0
operator_intent_capture_performed=0
operator_intent_record_write_enabled=0
operator_intent_record_written=0
operator_intent_evidence_written=0
operator_intent_transcript_write_performed=0
implementation_gate_open=0
reset_uninstall_live_run_allowed=0
reset_uninstall_deletion_enabled=0
managed_target_removal_allowed=0
managed_target_deletion_enabled=0
reset_uninstall_receipt_write_enabled=0
macos_reset_uninstall_implementation_gate_contract_present=1
implementation_gate_contract_state=closed-no-effect
implementation_gate_decision=blocked-missing-reset-uninstall-evidence
macos_reset_uninstall_receipt_schema_contract_present=1
macos_reset_uninstall_absence_report_contract_present=1
macos_reset_uninstall_dry_run_planner_present=1
reset_uninstall_dry_run_planner_transcript_present=1
macos_reset_uninstall_live_target_classifier_present=1
macos_reset_uninstall_dry_run_contract_present=1
macos_verification_transcript_contract_present=1
macos_commit_gate_contract_present=1
reset_uninstall_dry_run_evidence_present=0
reset_uninstall_receipt_evidence_present=0
reset_receipt_evidence_present=0
receipt_schema_evidence_present=0
absence_report_evidence_present=0
reset_uninstall_implementation_present=0
macos_reset_uninstall_implemented=0
app_support_prefix_target=$HOME/Library/Application Support/Latticra
app_bundle_target=$HOME/Applications/Latticra Panel.app
cli_wrapper_target=$HOME/.local/bin/latticra-panel
reset_receipts_dir_target=$HOME/Library/Application Support/Latticra Reset Receipts
reset_receipt_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/reset-uninstall-receipt.json
absence_report_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/absence-report.txt
operator_intent_evidence_format=text-transcript
operator_intent_schema_version=macos-reset-uninstall-operator-intent/1
operator_intent_digest_algorithm=sha256
operator_intent_must_be_explicit=1
operator_intent_must_be_current_session=1
operator_intent_must_not_be_inferred=1
operator_intent_must_not_be_defaulted=1
operator_intent_must_not_be_from_previous_session=1
operator_intent_must_name_operation=1
operator_intent_operation_values=reset,uninstall
operator_intent_must_name_target_scope=1
operator_intent_target_scope=user-local-managed-targets-only
operator_intent_must_acknowledge_managed_targets_only=1
operator_intent_must_acknowledge_no_unmanaged_removal=1
operator_intent_must_acknowledge_receipt_path=1
operator_intent_must_acknowledge_absence_report_path=1
operator_intent_must_acknowledge_no_network=1
operator_intent_must_acknowledge_no_root=1
operator_intent_must_acknowledge_live_classifier_digest=1
operator_intent_must_acknowledge_dry_run_planner_digest=1
operator_intent_field_dry_run_planner_transcript_digest_required=1
operator_intent_field_live_classifier_digest_required=1
operator_intent_field_receipt_schema_digest_required=1
operator_intent_field_absence_report_contract_digest_required=1
operator_intent_field_confirmation_text_required=1
operator_intent_scope_must_match_live_classifier=1
operator_intent_scope_must_match_dry_run_planner=1
operator_intent_confirmation_phrase_required=1
operator_intent_confirmation_phrase_future=reset-or-uninstall-latticra-user-local-managed-targets
operator_intent_transcript_required=1
operator_intent_phase_1=present_live_target_classifier_summary
operator_intent_phase_2=present_dry_run_planner_summary
operator_intent_phase_3=present_receipt_and_absence_report_paths
operator_intent_phase_4=request_explicit_operator_intent
operator_intent_phase_5=record_operator_intent_evidence
operator_intent_phase_6=allow_future_implementation_gate_open
operator_intent_phase_1_status=contract-only
operator_intent_phase_2_status=contract-only
operator_intent_phase_3_status=contract-only
operator_intent_phase_4_status=contract-only
operator_intent_phase_5_status=disabled
operator_intent_phase_6_status=disabled
managed_marker_required=1
unmanaged_target_preservation_required=1
receipt_outside_removed_prefix_required=1
absence_report_required=1
managed_wrapper_removal_performed=0
managed_app_bundle_removal_performed=0
managed_application_support_removal_performed=0
reset_receipt_write_performed=0
absence_report_run_performed=0
absence_report_written=0
file_delete_performed=0
directory_delete_performed=0
application_support_write_performed=0
receipt_write_performed=0
app_bundle_write_performed=0
cli_wrapper_write_performed=0
shell_profile_mutation_performed=0
host_mutation_performed=0
network_performed=0
root_authority=0
launchagent_authority=0
keychain_authority=0
tcc_bypass_authority=0
endpoint_security_authority=0
system_extension_authority=0
network_extension_authority=0
privileged_helper_authority=0
runtime_authority_granted=0
production_installer_ready=0
next_lane=macos-reset-uninstall-live-runner-interface-contract
REPORT
