#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

usage() {
  cat <<'USAGE'
Usage:
  macos-reset-uninstall-live-runner-interface-contract.sh

Emits the no-effect macOS reset/uninstall live-runner interface contract.
It defines the future live-runner entrypoint and input contract, but accepts
only a passed preflight. Because the current preflight is blocked, runner
invocation, deletion, receipt writes, absence-report writes, and host mutation
remain disabled.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
UNAME_S=$(uname -s 2>/dev/null || printf 'unknown')
UNAME_M=$(uname -m 2>/dev/null || printf 'unknown')

cat <<REPORT
MACOS RESET UNINSTALL LIVE RUNNER INTERFACE CONTRACT

reset_uninstall_live_runner_interface_contract_status=ok
macos_reset_uninstall_live_runner_interface_contract_present=1
repo_root=$ROOT
host_kernel_name=$UNAME_S
host_arch=$UNAME_M
live_runner_interface_contract_state=defined-no-effect
live_runner_interface_contract_decision=denied-current-preflight-not-passed
live_runner_interface_required=1
live_runner_interface_present=1
live_runner_interface_entrypoint_defined=1
live_runner_interface_entrypoint_name=latticra-macos-reset-uninstall-live-runner
live_runner_interface_accepts_only_passed_preflight=1
live_runner_interface_accepts_passed_preflight_only=1
live_runner_interface_preflight_present=1
live_runner_interface_preflight_passed=0
live_runner_interface_denial_transcript_present=1
live_runner_interface_denial_transcript_recorded=1
live_runner_interface_invocation_enabled=0
live_runner_interface_handoff_enabled=0
live_runner_interface_runner_enabled=0
live_runner_interface_deletion_enabled=0
live_runner_interface_receipt_write_enabled=0
live_runner_interface_absence_write_enabled=0
live_runner_interface_absence_report_write_enabled=0
live_runner_interface_denial_path_active=1
live_runner_interface_accept_path_active=0
live_runner_interface_effect=none
live_runner_interface_effect_authorization_required=1
live_runner_interface_effect_authorized=0
reset_uninstall_live_run_allowed=0
reset_uninstall_deletion_enabled=0
managed_target_removal_allowed=0
managed_target_deletion_enabled=0
reset_uninstall_receipt_write_enabled=0
absence_report_write_enabled=0
macos_reset_uninstall_live_denial_transcript_contract_present=1
macos_reset_uninstall_live_runner_interface_contract_present=1
live_denial_transcript_contract_state=recorded-no-effect
live_denial_transcript_contract_decision=denied-by-preflight-block
live_denial_transcript_recorded=1
live_denial_transcript_stdout_only=1
live_denial_transcript_file_write_enabled=0
live_runner_interface_contract_state=defined-no-effect
live_runner_interface_current_preflight_passed=0
live_runner_interface_current_decision=deny
live_runner_interface_dispatch_enabled=0
live_runner_interface_runner_handoff_enabled=0
live_denial_transcript_preflight_passed=0
live_denial_transcript_denial_reason=missing-complete-evidence-bundle-and-effect-authorization
macos_reset_uninstall_live_execution_preflight_contract_present=1
live_execution_preflight_contract_state=closed-no-effect
live_execution_preflight_contract_decision=blocked-missing-complete-evidence-bundle-and-effect-authorization
live_execution_preflight_required=1
live_execution_preflight_present=1
live_execution_preflight_passed=0
live_execution_preflight_blocking=1
live_execution_preflight_evidence_present=0
live_execution_preflight_record_write_enabled=0
live_execution_preflight_denial_recorded=1
live_execution_preflight_denial_reason=missing-complete-evidence-bundle-and-effect-authorization
macos_reset_uninstall_live_implementation_plan_contract_present=1
live_implementation_plan_contract_state=defined-no-effect
live_implementation_plan_execution_enabled=0
live_implementation_plan_deletion_enabled=0
live_implementation_plan_preflight_present=1
live_implementation_plan_preflight_passed=0
macos_reset_uninstall_evidence_bundle_contract_present=1
evidence_bundle_contract_state=defined-no-effect
reset_uninstall_evidence_bundle_complete=0
evidence_bundle_complete=0
reset_uninstall_evidence_bundle_valid=0
reset_uninstall_evidence_bundle_evidence_present=0
macos_reset_uninstall_effect_authorization_contract_present=1
effect_authorization_contract_state=closed-no-effect
effect_authorization_open=0
reset_uninstall_effect_authorized=0
macos_reset_uninstall_implementation_gate_contract_present=1
implementation_gate_contract_state=closed-no-effect
implementation_gate_open=0
macos_reset_uninstall_operator_intent_contract_present=1
operator_intent_contract_state=defined-no-effect
operator_reset_uninstall_intent_evidence_present=0
operator_explicit_reset_uninstall_intent_observed=0
macos_reset_uninstall_dry_run_planner_present=1
reset_uninstall_dry_run_planner_transcript_present=1
macos_reset_uninstall_live_target_classifier_present=1
macos_reset_uninstall_receipt_schema_contract_present=1
macos_reset_uninstall_absence_report_contract_present=1
macos_reset_uninstall_dry_run_contract_present=1
macos_verification_transcript_contract_present=1
macos_commit_gate_contract_present=1
app_support_prefix_target=$HOME/Library/Application Support/Latticra
app_bundle_target=$HOME/Applications/Latticra Panel.app
cli_wrapper_target=$HOME/.local/bin/latticra-panel
reset_receipts_dir_target=$HOME/Library/Application Support/Latticra Reset Receipts
reset_receipt_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/reset-uninstall-receipt.json
absence_report_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/absence-report.txt
live_runner_interface_schema_version=macos-reset-uninstall-live-runner-interface/1
live_runner_interface_required_input_count=8
live_runner_interface_observed_input_count=8
live_runner_interface_requires_passed_preflight=1
live_runner_interface_requires_live_denial_transcript=1
live_runner_interface_requires_complete_evidence_bundle=1
live_runner_interface_requires_effect_authorization=1
live_runner_interface_requires_implementation_gate_open=1
live_runner_interface_requires_operator_intent_evidence=1
live_runner_interface_requires_denial_transcript_when_blocked=1
live_runner_interface_requires_managed_targets_only=1
live_runner_interface_requires_receipt_schema=1
live_runner_interface_requires_absence_report_contract=1
live_runner_interface_requires_no_unmanaged_targets=1
live_runner_interface_requires_no_unsafe_paths=1
live_runner_interface_requires_no_deletion=1
live_runner_interface_requires_no_network=1
live_runner_interface_requires_no_root=1
live_runner_interface_condition_passed_preflight=required
live_runner_interface_condition_live_denial_transcript=present
live_runner_interface_condition_complete_evidence_bundle=required
live_runner_interface_condition_effect_authorization=required
live_runner_interface_condition_implementation_gate_open=required
live_runner_interface_condition_operator_intent_evidence=required
live_runner_interface_condition_no_unmanaged_targets=required
live_runner_interface_condition_no_deletion=required
live_runner_interface_condition_denial_transcript_when_blocked=required
live_runner_interface_condition_no_deletion_without_accept=required
live_runner_interface_condition_no_receipt_write_without_accept=required
live_runner_interface_condition_no_absence_report_write_without_accept=required
live_runner_interface_condition_no_network=required
live_runner_interface_condition_no_root=required
live_runner_interface_result_passed_preflight=not_met
live_runner_interface_result_live_denial_transcript=met
live_runner_interface_result_complete_evidence_bundle=not_met
live_runner_interface_result_effect_authorization=not_met
live_runner_interface_result_implementation_gate_open=not_met
live_runner_interface_result_operator_intent_evidence=not_met
live_runner_interface_result_no_unmanaged_targets=not_evaluated_contract_only
live_runner_interface_result_no_deletion=met
live_runner_interface_result_denial_transcript_when_blocked=met
live_runner_interface_result_no_deletion_without_accept=met
live_runner_interface_result_no_receipt_write_without_accept=met
live_runner_interface_result_no_absence_report_write_without_accept=met
live_runner_interface_result_no_network=met
live_runner_interface_result_no_root=met
live_runner_interface_input_preflight_status=required-passed
live_runner_interface_input_denial_transcript=required-when-blocked
live_runner_interface_input_target_plan=managed-targets-only
live_runner_interface_output_on_block=stdout-denial-only
live_runner_interface_output_on_pass=future-effect-handled-by-gated-runner
live_runner_interface_phase_1=accept_invocation_request
live_runner_interface_phase_2=load_live_execution_preflight
live_runner_interface_phase_3=reject_failed_preflight
live_runner_interface_phase_4=emit_denial_transcript_reference
live_runner_interface_phase_5=block_effect_dispatch
live_runner_interface_phase_1_status=contract-only
live_runner_interface_phase_2_status=contract-only
live_runner_interface_phase_3_status=blocked-preflight-not-passed
live_runner_interface_phase_4_status=recorded-no-effect
live_runner_interface_phase_5_status=blocked-no-effect
reset_uninstall_implementation_present=0
macos_reset_uninstall_implemented=0
live_reset_uninstall_runner_present=0
live_reset_uninstall_runner_enabled=0
managed_marker_required=1
unmanaged_target_preservation_required=1
receipt_outside_removed_prefix_required=1
absence_report_required=1
managed_wrapper_removal_performed=0
managed_app_bundle_removal_performed=0
managed_application_support_removal_performed=0
reset_receipt_write_performed=0
absence_report_run_performed=0
absence_report_written=0
file_delete_performed=0
directory_delete_performed=0
application_support_write_performed=0
receipt_write_performed=0
app_bundle_write_performed=0
cli_wrapper_write_performed=0
shell_profile_mutation_performed=0
host_mutation_performed=0
network_performed=0
root_authority=0
launchagent_authority=0
keychain_authority=0
tcc_bypass_authority=0
endpoint_security_authority=0
system_extension_authority=0
network_extension_authority=0
privileged_helper_authority=0
runtime_authority_granted=0
production_installer_ready=0
next_lane=macos-reset-uninstall-live-runner-acceptance-gate-contract
REPORT
