#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

usage() {
  cat <<'USAGE'
Usage:
  macos-reset-uninstall-live-runner-denied-dispatch-transcript-contract.sh

Emits the no-effect macOS reset/uninstall live-runner denied-dispatch
transcript contract. It records that the no-op runner prototype reached only
the denied interface path and that effect dispatch remains disabled.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
UNAME_S=$(uname -s 2>/dev/null || printf 'unknown')
UNAME_M=$(uname -m 2>/dev/null || printf 'unknown')

cat <<REPORT
MACOS RESET UNINSTALL LIVE RUNNER DENIED DISPATCH TRANSCRIPT CONTRACT

reset_uninstall_live_runner_denied_dispatch_transcript_contract_status=ok
macos_reset_uninstall_live_runner_denied_dispatch_transcript_contract_present=1
repo_root=$ROOT
host_kernel_name=$UNAME_S
host_arch=$UNAME_M
live_runner_denied_dispatch_transcript_contract_state=recorded-no-effect
live_runner_denied_dispatch_transcript_contract_decision=dispatch-denied-no-effects-recorded
live_runner_denied_dispatch_transcript_required=1
live_runner_denied_dispatch_transcript_present=1
live_runner_denied_dispatch_transcript_recorded=1
live_runner_denied_dispatch_transcript_stdout_only=1
live_runner_denied_dispatch_transcript_file_write_enabled=0
live_runner_denied_dispatch_transcript_dispatch_attempted=0
live_runner_denied_dispatch_transcript_dispatch_enabled=0
live_runner_denied_dispatch_transcript_dispatch_denied=1
live_runner_denied_dispatch_transcript_denial_reason=failed-preflight-and-denied-interface
live_runner_denied_dispatch_transcript_denial_source=macos-reset-uninstall-live-runner-noop-prototype-contract
live_runner_denied_dispatch_transcript_effect=none
live_runner_denied_dispatch_transcript_noop_prototype_present=1
live_runner_denied_dispatch_transcript_noop_denial_path_exercised=1
live_runner_denied_dispatch_transcript_noop_dispatch_enabled=0
live_runner_denied_dispatch_transcript_noop_deletion_enabled=0
reset_uninstall_live_run_allowed=0
reset_uninstall_deletion_enabled=0
managed_target_removal_allowed=0
managed_target_deletion_enabled=0
reset_uninstall_receipt_write_enabled=0
absence_report_write_enabled=0
macos_reset_uninstall_live_runner_noop_prototype_contract_present=1
live_runner_noop_prototype_contract_state=executed-no-effect
live_runner_noop_prototype_contract_decision=denied-interface-path-only
live_runner_noop_prototype_invocation_simulated=1
live_runner_noop_prototype_stdout_only=1
live_runner_noop_prototype_dispatch_enabled=0
live_runner_noop_prototype_runner_enabled=0
live_runner_noop_prototype_runner_effect_enabled=0
live_runner_noop_prototype_deletion_enabled=0
live_runner_noop_prototype_receipt_write_enabled=0
live_runner_noop_prototype_absence_report_write_enabled=0
live_runner_noop_prototype_denial_path_exercised=1
live_runner_noop_prototype_accept_path_exercised=0
live_runner_noop_prototype_effect=none
live_runner_noop_prototype_effect_authorized=0
live_runner_noop_prototype_preflight_passed=0
live_runner_noop_prototype_interface_present=1
live_runner_noop_prototype_interface_denial_path_active=1
live_runner_noop_prototype_no_effects_performed=1
macos_reset_uninstall_live_runner_interface_contract_present=1
live_runner_interface_contract_state=defined-no-effect
live_runner_interface_contract_decision=denied-current-preflight-not-passed
live_runner_interface_accepts_passed_preflight_only=1
live_runner_interface_preflight_passed=0
live_runner_interface_denial_path_active=1
live_runner_interface_invocation_enabled=0
live_runner_interface_handoff_enabled=0
live_runner_interface_deletion_enabled=0
macos_reset_uninstall_live_denial_transcript_contract_present=1
live_denial_transcript_contract_state=recorded-no-effect
live_denial_transcript_recorded=1
live_denial_transcript_stdout_only=1
macos_reset_uninstall_live_execution_preflight_contract_present=1
live_execution_preflight_contract_state=closed-no-effect
live_execution_preflight_passed=0
live_execution_preflight_blocking=1
live_execution_preflight_denial_reason=missing-complete-evidence-bundle-and-effect-authorization
macos_reset_uninstall_evidence_bundle_contract_present=1
reset_uninstall_evidence_bundle_complete=0
macos_reset_uninstall_effect_authorization_contract_present=1
effect_authorization_open=0
reset_uninstall_effect_authorized=0
macos_reset_uninstall_operator_intent_contract_present=1
operator_reset_uninstall_intent_evidence_present=0
app_support_prefix_target=$HOME/Library/Application Support/Latticra
app_bundle_target=$HOME/Applications/Latticra Panel.app
cli_wrapper_target=$HOME/.local/bin/latticra-panel
reset_receipts_dir_target=$HOME/Library/Application Support/Latticra Reset Receipts
reset_receipt_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/reset-uninstall-receipt.json
absence_report_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/absence-report.txt
live_runner_denied_dispatch_transcript_schema_version=macos-reset-uninstall-live-runner-denied-dispatch-transcript/1
live_runner_denied_dispatch_transcript_required_input_count=6
live_runner_denied_dispatch_transcript_observed_input_count=6
live_runner_denied_dispatch_transcript_requires_noop_prototype=1
live_runner_denied_dispatch_transcript_requires_denied_dispatch=1
live_runner_denied_dispatch_transcript_requires_denial_reason=1
live_runner_denied_dispatch_transcript_requires_stdout_only=1
live_runner_denied_dispatch_transcript_requires_no_deletion=1
live_runner_denied_dispatch_transcript_requires_no_receipt_write=1
live_runner_denied_dispatch_transcript_requires_no_absence_report_write=1
live_runner_denied_dispatch_transcript_requires_no_network=1
live_runner_denied_dispatch_transcript_requires_no_root=1
live_runner_denied_dispatch_transcript_result_noop_prototype=met
live_runner_denied_dispatch_transcript_result_denied_dispatch=met
live_runner_denied_dispatch_transcript_result_denial_reason=met
live_runner_denied_dispatch_transcript_result_stdout_only=met
live_runner_denied_dispatch_transcript_result_no_deletion=met
live_runner_denied_dispatch_transcript_result_no_receipt_write=met
live_runner_denied_dispatch_transcript_result_no_absence_report_write=met
live_runner_denied_dispatch_transcript_result_no_network=met
live_runner_denied_dispatch_transcript_result_no_root=met
live_runner_denied_dispatch_transcript_entry_1=noop_prototype_present
live_runner_denied_dispatch_transcript_entry_2=runner_interface_denied
live_runner_denied_dispatch_transcript_entry_3=preflight_not_passed
live_runner_denied_dispatch_transcript_entry_4=dispatch_blocked
live_runner_denied_dispatch_transcript_entry_5=no_effects_performed
live_runner_denied_dispatch_transcript_entry_1_status=met
live_runner_denied_dispatch_transcript_entry_2_status=met
live_runner_denied_dispatch_transcript_entry_3_status=met
live_runner_denied_dispatch_transcript_entry_4_status=recorded
live_runner_denied_dispatch_transcript_entry_5_status=met
live_runner_denied_dispatch_transcript_phase_1=load_noop_prototype
live_runner_denied_dispatch_transcript_phase_2=record_denied_dispatch
live_runner_denied_dispatch_transcript_phase_3=preserve_no_effect_boundary
live_runner_denied_dispatch_transcript_phase_4=handoff_to_denied_dispatch_review
live_runner_denied_dispatch_transcript_phase_1_status=contract-only
live_runner_denied_dispatch_transcript_phase_2_status=stdout-only
live_runner_denied_dispatch_transcript_phase_3_status=blocked-no-effect
live_runner_denied_dispatch_transcript_phase_4_status=future-review-only
reset_uninstall_implementation_present=0
macos_reset_uninstall_implemented=0
live_reset_uninstall_runner_present=0
live_reset_uninstall_runner_enabled=0
managed_wrapper_removal_performed=0
managed_app_bundle_removal_performed=0
managed_application_support_removal_performed=0
reset_receipt_write_performed=0
absence_report_run_performed=0
absence_report_written=0
file_delete_performed=0
directory_delete_performed=0
application_support_write_performed=0
receipt_write_performed=0
app_bundle_write_performed=0
cli_wrapper_write_performed=0
shell_profile_mutation_performed=0
host_mutation_performed=0
network_performed=0
root_authority=0
runtime_authority_granted=0
production_installer_ready=0
next_lane=macos-reset-uninstall-live-runner-denied-dispatch-review-contract
REPORT
