#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

usage() {
  cat <<'USAGE'
Usage:
  macos-reset-uninstall-live-runner-acceptance-denial-disposition-closeout-audit-contract.sh

Emits the no-effect macOS reset/uninstall live-runner acceptance-denial
disposition closeout audit contract. It audits the no-effect closeout as stdout
evidence only and keeps runner dispatch, deletion, receipt writes,
absence-report writes, network access, root action, runtime authority, and host
mutation disabled.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
UNAME_S=$(uname -s 2>/dev/null || printf 'unknown')
UNAME_M=$(uname -m 2>/dev/null || printf 'unknown')

cat <<REPORT
MACOS RESET UNINSTALL LIVE RUNNER ACCEPTANCE DENIAL DISPOSITION CLOSEOUT AUDIT CONTRACT

reset_uninstall_live_runner_acceptance_denial_disposition_closeout_audit_contract_status=ok
macos_reset_uninstall_live_runner_acceptance_denial_disposition_closeout_audit_contract_present=1
repo_root=$ROOT
host_kernel_name=$UNAME_S
host_arch=$UNAME_M
live_runner_acceptance_denial_disposition_closeout_audit_contract_state=audited-no-effect-closeout
live_runner_acceptance_denial_disposition_closeout_audit_contract_decision=no-effect-closeout-audit-keeps-dispatch-closed
live_runner_acceptance_denial_disposition_closeout_audit_required=1
live_runner_acceptance_denial_disposition_closeout_audit_present=1
live_runner_acceptance_denial_disposition_closeout_audit_completed=1
live_runner_acceptance_denial_disposition_closeout_audit_recorded=1
live_runner_acceptance_denial_disposition_closeout_audit_stdout_only=1
live_runner_acceptance_denial_disposition_closeout_audit_file_write_enabled=0
live_runner_acceptance_denial_disposition_closeout_audit_audit_file_write_enabled=0
live_runner_acceptance_denial_disposition_closeout_audit_scope=audit-no-effect-closeout-only
live_runner_acceptance_denial_disposition_closeout_audit_source=macos-reset-uninstall-live-runner-acceptance-denial-disposition-review-contract
live_runner_acceptance_denial_disposition_closeout_audit_source_contract=macos-reset-uninstall-live-runner-acceptance-denial-disposition-review-contract
live_runner_acceptance_denial_disposition_closeout_audit_review_present=1
live_runner_acceptance_denial_disposition_closeout_audit_review_state=reviewed-no-effect
live_runner_acceptance_denial_disposition_closeout_audit_review_completed=1
live_runner_acceptance_denial_disposition_closeout_audit_review_recorded=1
live_runner_acceptance_denial_disposition_closeout_audit_review_stdout_only=1
live_runner_acceptance_denial_disposition_closeout_audit_review_file_write_enabled=0
live_runner_acceptance_denial_disposition_closeout_audit_review_closeout_opened=0
live_runner_acceptance_denial_disposition_closeout_audit_disposition_present=1
live_runner_acceptance_denial_disposition_closeout_audit_disposition_state=disposed-no-effect
live_runner_acceptance_denial_disposition_closeout_audit_disposition_decision=closed-gate-denial-disposed-no-dispatch
live_runner_acceptance_denial_disposition_closeout_audit_disposition_recorded=1
live_runner_acceptance_denial_disposition_closeout_audit_disposition_reviewed=1
live_runner_acceptance_denial_disposition_closeout_audit_disposition_applied=0
live_runner_acceptance_denial_disposition_closeout_audit_disposition_opens_dispatch=0
live_runner_acceptance_denial_disposition_closeout_audit_disposition_releases_runner=0
live_runner_acceptance_denial_disposition_closeout_required=1
live_runner_acceptance_denial_disposition_closeout_present=1
live_runner_acceptance_denial_disposition_closeout_state=closed-no-effect
live_runner_acceptance_denial_disposition_closeout_recorded=1
live_runner_acceptance_denial_disposition_closeout_audited=1
live_runner_acceptance_denial_disposition_closeout_applied=0
live_runner_acceptance_denial_disposition_closeout_opens_dispatch=0
live_runner_acceptance_denial_disposition_closeout_releases_runner=0
live_runner_acceptance_denial_disposition_closeout_requires_future_audit_review=1
live_runner_acceptance_denial_disposition_closeout_audit_closed_gate_reviewed=1
live_runner_acceptance_denial_disposition_closeout_audit_denial_reason_present=1
live_runner_acceptance_denial_disposition_closeout_audit_denial_reason_reviewed=1
live_runner_acceptance_denial_disposition_closeout_audit_acceptance_gate_open=0
live_runner_acceptance_denial_disposition_closeout_audit_acceptance_gate_closed=1
live_runner_acceptance_denial_disposition_closeout_audit_dispatch_audited=1
live_runner_acceptance_denial_disposition_closeout_audit_dispatch_reviewed=1
live_runner_acceptance_denial_disposition_closeout_audit_dispatch_allowed=0
live_runner_acceptance_denial_disposition_closeout_audit_dispatch_enabled=0
live_runner_acceptance_denial_disposition_closeout_audit_dispatch_performed=0
live_runner_acceptance_denial_disposition_closeout_audit_runner_handoff_enabled=0
live_runner_acceptance_denial_disposition_closeout_audit_deletion_enabled=0
live_runner_acceptance_denial_disposition_closeout_audit_receipt_write_enabled=0
live_runner_acceptance_denial_disposition_closeout_audit_absence_report_write_enabled=0
live_runner_acceptance_denial_disposition_closeout_audit_effect=none
live_runner_acceptance_denial_disposition_closeout_audit_effect_authorized=0
live_runner_acceptance_denial_disposition_closeout_audit_effect_boundary_preserved=1
live_runner_acceptance_denial_disposition_closeout_audit_audit_review_opened=0
live_runner_acceptance_denial_disposition_closeout_audit_result=no-effect-closeout-audit-boundary-preserved
reset_uninstall_live_run_allowed=0
reset_uninstall_deletion_enabled=0
managed_target_removal_allowed=0
managed_target_deletion_enabled=0
reset_uninstall_receipt_write_enabled=0
absence_report_write_enabled=0
macos_reset_uninstall_live_runner_acceptance_denial_disposition_review_contract_present=1
live_runner_acceptance_denial_disposition_review_contract_state=reviewed-no-effect
live_runner_acceptance_denial_disposition_review_contract_decision=no-effect-disposition-review-keeps-dispatch-closed
live_runner_acceptance_denial_disposition_review_completed=1
live_runner_acceptance_denial_disposition_review_recorded=1
live_runner_acceptance_denial_disposition_review_stdout_only=1
live_runner_acceptance_denial_disposition_review_file_write_enabled=0
live_runner_acceptance_denial_disposition_review_disposition_present=1
live_runner_acceptance_denial_disposition_review_disposition_state=disposed-no-effect
live_runner_acceptance_denial_disposition_review_disposition_reviewed=1
live_runner_acceptance_denial_disposition_review_disposition_applied=0
live_runner_acceptance_denial_disposition_review_disposition_opens_dispatch=0
live_runner_acceptance_denial_disposition_review_disposition_releases_runner=0
live_runner_acceptance_denial_disposition_review_acceptance_gate_open=0
live_runner_acceptance_denial_disposition_review_acceptance_gate_closed=1
live_runner_acceptance_denial_disposition_review_dispatch_enabled=0
live_runner_acceptance_denial_disposition_review_dispatch_performed=0
live_runner_acceptance_denial_disposition_review_deletion_enabled=0
live_runner_acceptance_denial_disposition_review_closeout_opened=0
macos_reset_uninstall_live_runner_acceptance_denial_disposition_contract_present=1
live_runner_acceptance_denial_disposition_contract_state=disposed-no-effect
live_runner_acceptance_denial_disposition_contract_decision=closed-gate-denial-disposed-no-dispatch
live_runner_acceptance_denial_disposition_recorded=1
live_runner_acceptance_denial_disposition_stdout_only=1
live_runner_acceptance_denial_disposition_file_write_enabled=0
live_runner_acceptance_denial_disposition_record_write_enabled=0
live_runner_acceptance_denial_disposition_acceptance_gate_open=0
live_runner_acceptance_denial_disposition_acceptance_gate_closed=1
live_runner_acceptance_denial_disposition_dispatch_allowed=0
live_runner_acceptance_denial_disposition_dispatch_enabled=0
live_runner_acceptance_denial_disposition_dispatch_performed=0
live_runner_acceptance_denial_disposition_deletion_enabled=0
live_runner_acceptance_denial_disposition_receipt_write_enabled=0
live_runner_acceptance_denial_disposition_absence_report_write_enabled=0
live_runner_acceptance_denial_disposition_applied=0
live_runner_acceptance_denial_disposition_opens_dispatch=0
live_runner_acceptance_denial_disposition_releases_runner=0
macos_reset_uninstall_live_runner_acceptance_denial_review_contract_present=1
live_runner_acceptance_denial_review_contract_state=reviewed-no-effect
live_runner_acceptance_denial_review_contract_decision=closed-gate-review-retains-zero-dispatch
live_runner_acceptance_denial_review_completed=1
live_runner_acceptance_denial_review_acceptance_gate_open=0
live_runner_acceptance_denial_review_dispatch_enabled=0
live_runner_acceptance_denial_review_dispatch_performed=0
live_runner_acceptance_denial_review_deletion_enabled=0
macos_reset_uninstall_live_runner_acceptance_denial_transcript_contract_present=1
live_runner_acceptance_denial_transcript_contract_state=recorded-no-effect
live_runner_acceptance_denial_transcript_acceptance_gate_open=0
live_runner_acceptance_denial_transcript_dispatch_enabled=0
live_runner_acceptance_denial_transcript_dispatch_performed=0
live_runner_acceptance_denial_transcript_deletion_enabled=0
macos_reset_uninstall_live_runner_acceptance_gate_contract_present=1
live_runner_acceptance_gate_contract_state=closed-no-effect
live_runner_acceptance_gate_open=0
live_runner_acceptance_gate_closed=1
live_runner_acceptance_gate_dispatch_allowed=0
live_runner_acceptance_gate_dispatch_enabled=0
live_runner_acceptance_gate_dispatch_performed=0
live_runner_acceptance_gate_deletion_enabled=0
macos_reset_uninstall_live_execution_preflight_contract_present=1
live_execution_preflight_contract_state=closed-no-effect
live_execution_preflight_passed=0
live_execution_preflight_blocking=1
macos_reset_uninstall_evidence_bundle_contract_present=1
evidence_bundle_complete=0
reset_uninstall_evidence_bundle_complete=0
macos_reset_uninstall_effect_authorization_contract_present=1
effect_authorization_open=0
reset_uninstall_effect_authorized=0
macos_reset_uninstall_operator_intent_contract_present=1
operator_reset_uninstall_intent_evidence_present=0
operator_explicit_reset_uninstall_intent_observed=0
reset_uninstall_implementation_present=0
macos_reset_uninstall_implemented=0
app_support_prefix_target=$HOME/Library/Application Support/Latticra
app_bundle_target=$HOME/Applications/Latticra Panel.app
cli_wrapper_target=$HOME/.local/bin/latticra-panel
reset_receipts_dir_target=$HOME/Library/Application Support/Latticra Reset Receipts
reset_receipt_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/reset-uninstall-receipt.json
absence_report_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/absence-report.txt
live_runner_acceptance_denial_disposition_closeout_audit_schema_version=macos-reset-uninstall-live-runner-acceptance-denial-disposition-closeout-audit/1
live_runner_acceptance_denial_disposition_closeout_audit_required_input_count=8
live_runner_acceptance_denial_disposition_closeout_audit_observed_input_count=8
live_runner_acceptance_denial_disposition_closeout_audit_requires_acceptance_denial_disposition=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_acceptance_denial_disposition_review=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_closed_gate=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_no_effect_closeout=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_audit_only=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_stdout_only=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_no_effects=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_no_dispatch=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_no_deletion=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_no_receipt_write=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_no_absence_report_write=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_no_network=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_no_root=1
live_runner_acceptance_denial_disposition_closeout_audit_requires_audit_review_handoff=1
live_runner_acceptance_denial_disposition_closeout_audit_result_acceptance_denial_disposition=met
live_runner_acceptance_denial_disposition_closeout_audit_result_acceptance_denial_disposition_review=met
live_runner_acceptance_denial_disposition_closeout_audit_result_closed_gate=met
live_runner_acceptance_denial_disposition_closeout_audit_result_no_effect_closeout=met
live_runner_acceptance_denial_disposition_closeout_audit_result_audit_only=met
live_runner_acceptance_denial_disposition_closeout_audit_result_stdout_only=met
live_runner_acceptance_denial_disposition_closeout_audit_result_no_effects=met
live_runner_acceptance_denial_disposition_closeout_audit_result_no_dispatch=met
live_runner_acceptance_denial_disposition_closeout_audit_result_no_deletion=met
live_runner_acceptance_denial_disposition_closeout_audit_result_no_receipt_write=met
live_runner_acceptance_denial_disposition_closeout_audit_result_no_absence_report_write=met
live_runner_acceptance_denial_disposition_closeout_audit_result_no_network=met
live_runner_acceptance_denial_disposition_closeout_audit_result_no_root=met
live_runner_acceptance_denial_disposition_closeout_audit_result_audit_review_handoff=met
live_runner_acceptance_denial_disposition_closeout_audit_entry_1=acceptance_denial_disposition_review_present
live_runner_acceptance_denial_disposition_closeout_audit_entry_2=no_effect_closeout_audited
live_runner_acceptance_denial_disposition_closeout_audit_entry_3=dispatch_remains_closed
live_runner_acceptance_denial_disposition_closeout_audit_entry_4=deletion_remains_disabled
live_runner_acceptance_denial_disposition_closeout_audit_entry_5=no_effects_confirmed
live_runner_acceptance_denial_disposition_closeout_audit_entry_6=audit_review_required
live_runner_acceptance_denial_disposition_closeout_audit_entry_1_status=met
live_runner_acceptance_denial_disposition_closeout_audit_entry_2_status=audited
live_runner_acceptance_denial_disposition_closeout_audit_entry_3_status=blocked-no-effect
live_runner_acceptance_denial_disposition_closeout_audit_entry_4_status=blocked-no-effect
live_runner_acceptance_denial_disposition_closeout_audit_entry_5_status=met
live_runner_acceptance_denial_disposition_closeout_audit_entry_6_status=recorded
live_runner_acceptance_denial_disposition_closeout_audit_phase_1=load_acceptance_denial_disposition_review
live_runner_acceptance_denial_disposition_closeout_audit_phase_2=audit_no_effect_closeout
live_runner_acceptance_denial_disposition_closeout_audit_phase_3=confirm_closed_dispatch_boundary
live_runner_acceptance_denial_disposition_closeout_audit_phase_4=handoff_to_acceptance_denial_disposition_closeout_audit_review
live_runner_acceptance_denial_disposition_closeout_audit_phase_1_status=contract-only
live_runner_acceptance_denial_disposition_closeout_audit_phase_2_status=audit-only
live_runner_acceptance_denial_disposition_closeout_audit_phase_3_status=blocked-no-effect
live_runner_acceptance_denial_disposition_closeout_audit_phase_4_status=future-review-only
live_reset_uninstall_runner_present=0
live_reset_uninstall_runner_enabled=0
managed_wrapper_removal_performed=0
managed_app_bundle_removal_performed=0
managed_application_support_removal_performed=0
reset_receipt_write_performed=0
absence_report_run_performed=0
absence_report_written=0
file_delete_performed=0
directory_delete_performed=0
application_support_write_performed=0
receipt_write_performed=0
app_bundle_write_performed=0
cli_wrapper_write_performed=0
shell_profile_mutation_performed=0
host_mutation_performed=0
network_performed=0
root_authority=0
runtime_authority_granted=0
production_installer_ready=0
next_lane=macos-reset-uninstall-live-runner-acceptance-denial-disposition-closeout-audit-review-disposition-contract
REPORT
