#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

usage() {
  cat <<'USAGE'
Usage:
  macos-reset-uninstall-live-runner-acceptance-denial-review-contract.sh

Emits the no-effect macOS reset/uninstall live-runner acceptance-denial review
contract. It reviews the closed acceptance-gate transcript as evidence only and
keeps runner dispatch, deletion, receipt writes, absence-report writes, network
access, root action, runtime authority, and host mutation disabled.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
UNAME_S=$(uname -s 2>/dev/null || printf 'unknown')
UNAME_M=$(uname -m 2>/dev/null || printf 'unknown')

cat <<REPORT
MACOS RESET UNINSTALL LIVE RUNNER ACCEPTANCE DENIAL REVIEW CONTRACT

reset_uninstall_live_runner_acceptance_denial_review_contract_status=ok
macos_reset_uninstall_live_runner_acceptance_denial_review_contract_present=1
repo_root=$ROOT
host_kernel_name=$UNAME_S
host_arch=$UNAME_M
live_runner_acceptance_denial_review_contract_state=reviewed-no-effect
live_runner_acceptance_denial_review_contract_decision=closed-gate-review-retains-zero-dispatch
live_runner_acceptance_denial_review_required=1
live_runner_acceptance_denial_review_present=1
live_runner_acceptance_denial_review_completed=1
live_runner_acceptance_denial_review_recorded=1
live_runner_acceptance_denial_review_stdout_only=1
live_runner_acceptance_denial_review_file_write_enabled=0
live_runner_acceptance_denial_review_review_file_write_enabled=0
live_runner_acceptance_denial_review_scope=review-closed-gate-transcript-only
live_runner_acceptance_denial_review_source=macos-reset-uninstall-live-runner-acceptance-denial-transcript-contract
live_runner_acceptance_denial_review_source_contract=macos-reset-uninstall-live-runner-acceptance-denial-transcript-contract
live_runner_acceptance_denial_review_closed_gate_transcript_present=1
live_runner_acceptance_denial_review_closed_gate_reviewed=1
live_runner_acceptance_denial_review_denial_reason_present=1
live_runner_acceptance_denial_review_denial_reason_reviewed=1
live_runner_acceptance_denial_review_acceptance_gate_open=0
live_runner_acceptance_denial_review_acceptance_gate_closed=1
live_runner_acceptance_denial_review_dispatch_reviewed=1
live_runner_acceptance_denial_review_dispatch_allowed=0
live_runner_acceptance_denial_review_dispatch_enabled=0
live_runner_acceptance_denial_review_dispatch_performed=0
live_runner_acceptance_denial_review_runner_handoff_enabled=0
live_runner_acceptance_denial_review_deletion_enabled=0
live_runner_acceptance_denial_review_receipt_write_enabled=0
live_runner_acceptance_denial_review_absence_report_write_enabled=0
live_runner_acceptance_denial_review_effect=none
live_runner_acceptance_denial_review_effect_authorized=0
live_runner_acceptance_denial_review_effect_boundary_preserved=1
live_runner_acceptance_denial_review_disposition_opened=0
live_runner_acceptance_denial_review_result=closed-gate-boundary-preserved
reset_uninstall_live_run_allowed=0
reset_uninstall_deletion_enabled=0
managed_target_removal_allowed=0
managed_target_deletion_enabled=0
reset_uninstall_receipt_write_enabled=0
absence_report_write_enabled=0
macos_reset_uninstall_live_runner_acceptance_denial_transcript_contract_present=1
live_runner_acceptance_denial_transcript_contract_state=recorded-no-effect
live_runner_acceptance_denial_transcript_contract_decision=acceptance-gate-closed-no-dispatch-recorded
live_runner_acceptance_denial_transcript_recorded=1
live_runner_acceptance_denial_transcript_stdout_only=1
live_runner_acceptance_denial_transcript_file_write_enabled=0
live_runner_acceptance_denial_transcript_acceptance_gate_open=0
live_runner_acceptance_denial_transcript_acceptance_gate_closed=1
live_runner_acceptance_denial_transcript_dispatch_allowed=0
live_runner_acceptance_denial_transcript_dispatch_enabled=0
live_runner_acceptance_denial_transcript_dispatch_performed=0
live_runner_acceptance_denial_transcript_deletion_enabled=0
live_runner_acceptance_denial_transcript_denial_reason=missing-passed-preflight-complete-evidence-effect-authorization-operator-intent-and-implementation
live_runner_acceptance_denial_transcript_denial_source=macos-reset-uninstall-live-runner-acceptance-gate-contract
live_runner_acceptance_denial_review_transcript_state=recorded-no-effect
live_runner_acceptance_denial_review_transcript_decision=acceptance-gate-closed-no-dispatch-recorded
live_runner_acceptance_denial_review_transcript_gate_open=0
live_runner_acceptance_denial_review_transcript_gate_closed=1
live_runner_acceptance_denial_review_transcript_dispatch_enabled=0
live_runner_acceptance_denial_review_transcript_dispatch_performed=0
live_runner_acceptance_denial_review_transcript_deletion_enabled=0
live_runner_acceptance_denial_review_transcript_denial_reason=missing-passed-preflight-complete-evidence-effect-authorization-operator-intent-and-implementation
live_runner_acceptance_denial_review_transcript_effect=none
live_runner_acceptance_denial_transcript_result_acceptance_gate=met
live_runner_acceptance_denial_transcript_result_closed_gate=met
live_runner_acceptance_denial_transcript_result_denial_reason=met
live_runner_acceptance_denial_transcript_result_no_dispatch=met
live_runner_acceptance_denial_transcript_result_no_deletion=met
live_runner_acceptance_denial_transcript_result_no_receipt_write=met
live_runner_acceptance_denial_transcript_result_no_absence_report_write=met
live_runner_acceptance_denial_transcript_result_no_network=met
live_runner_acceptance_denial_transcript_result_no_root=met
macos_reset_uninstall_live_runner_acceptance_gate_contract_present=1
live_runner_acceptance_gate_contract_state=closed-no-effect
live_runner_acceptance_gate_contract_decision=dispatch-blocked-missing-passed-preflight-evidence-and-authorization
live_runner_acceptance_gate_open=0
live_runner_acceptance_gate_closed=1
live_runner_acceptance_gate_acceptance_granted=0
live_runner_acceptance_gate_dispatch_allowed=0
live_runner_acceptance_gate_dispatch_enabled=0
live_runner_acceptance_gate_dispatch_performed=0
live_runner_acceptance_gate_deletion_enabled=0
live_runner_acceptance_gate_effect_authorized=0
live_runner_acceptance_gate_result_denied_dispatch_review=met
live_runner_acceptance_gate_result_passed_preflight=blocked
live_runner_acceptance_gate_result_complete_evidence_bundle=blocked
live_runner_acceptance_gate_result_effect_authorization=blocked
live_runner_acceptance_gate_result_operator_intent=blocked
live_runner_acceptance_gate_result_implementation=blocked
live_runner_acceptance_gate_result_no_dispatch_until_open=met
live_runner_acceptance_gate_result_no_deletion_until_open=met
macos_reset_uninstall_live_runner_denied_dispatch_review_contract_present=1
live_runner_denied_dispatch_review_contract_state=reviewed-no-effect
live_runner_denied_dispatch_review_dispatch_reviewed=1
live_runner_denied_dispatch_review_dispatch_denied=1
live_runner_denied_dispatch_review_dispatch_enabled=0
live_runner_denied_dispatch_review_dispatch_performed=0
live_runner_denied_dispatch_review_deletion_enabled=0
live_runner_denied_dispatch_review_acceptance_gate_opened=0
macos_reset_uninstall_live_execution_preflight_contract_present=1
live_execution_preflight_contract_state=closed-no-effect
live_execution_preflight_passed=0
live_execution_preflight_blocking=1
live_execution_preflight_denial_reason=missing-complete-evidence-bundle-and-effect-authorization
macos_reset_uninstall_evidence_bundle_contract_present=1
evidence_bundle_complete=0
reset_uninstall_evidence_bundle_complete=0
macos_reset_uninstall_effect_authorization_contract_present=1
effect_authorization_open=0
reset_uninstall_effect_authorized=0
macos_reset_uninstall_operator_intent_contract_present=1
operator_reset_uninstall_intent_evidence_present=0
operator_explicit_reset_uninstall_intent_observed=0
reset_uninstall_implementation_present=0
macos_reset_uninstall_implemented=0
app_support_prefix_target=$HOME/Library/Application Support/Latticra
app_bundle_target=$HOME/Applications/Latticra Panel.app
cli_wrapper_target=$HOME/.local/bin/latticra-panel
reset_receipts_dir_target=$HOME/Library/Application Support/Latticra Reset Receipts
reset_receipt_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/reset-uninstall-receipt.json
absence_report_path_future=$HOME/Library/Application Support/Latticra Reset Receipts/absence-report.txt
live_runner_acceptance_denial_review_schema_version=macos-reset-uninstall-live-runner-acceptance-denial-review/1
live_runner_acceptance_denial_review_required_input_count=7
live_runner_acceptance_denial_review_observed_input_count=7
live_runner_acceptance_denial_review_requires_acceptance_denial_transcript=1
live_runner_acceptance_denial_review_requires_closed_gate=1
live_runner_acceptance_denial_review_requires_denial_reason=1
live_runner_acceptance_denial_review_requires_review_only=1
live_runner_acceptance_denial_review_requires_stdout_only=1
live_runner_acceptance_denial_review_requires_no_effects=1
live_runner_acceptance_denial_review_requires_no_dispatch=1
live_runner_acceptance_denial_review_requires_no_deletion=1
live_runner_acceptance_denial_review_requires_no_receipt_write=1
live_runner_acceptance_denial_review_requires_no_absence_report_write=1
live_runner_acceptance_denial_review_requires_no_network=1
live_runner_acceptance_denial_review_requires_no_root=1
live_runner_acceptance_denial_review_requires_disposition_handoff=1
live_runner_acceptance_denial_review_result_acceptance_denial_transcript=met
live_runner_acceptance_denial_review_result_closed_gate=met
live_runner_acceptance_denial_review_result_denial_reason=met
live_runner_acceptance_denial_review_result_review_only=met
live_runner_acceptance_denial_review_result_stdout_only=met
live_runner_acceptance_denial_review_result_no_effects=met
live_runner_acceptance_denial_review_result_no_dispatch=met
live_runner_acceptance_denial_review_result_no_deletion=met
live_runner_acceptance_denial_review_result_no_receipt_write=met
live_runner_acceptance_denial_review_result_no_absence_report_write=met
live_runner_acceptance_denial_review_result_no_network=met
live_runner_acceptance_denial_review_result_no_root=met
live_runner_acceptance_denial_review_result_disposition_handoff=met
live_runner_acceptance_denial_review_entry_1=acceptance_denial_transcript_present
live_runner_acceptance_denial_review_entry_2=closed_gate_recorded
live_runner_acceptance_denial_review_entry_3=denial_reason_reviewed
live_runner_acceptance_denial_review_entry_4=acceptance_inputs_blocked
live_runner_acceptance_denial_review_entry_5=no_effects_confirmed
live_runner_acceptance_denial_review_entry_6=disposition_required
live_runner_acceptance_denial_review_entry_1_status=met
live_runner_acceptance_denial_review_entry_2_status=reviewed
live_runner_acceptance_denial_review_entry_3_status=reviewed
live_runner_acceptance_denial_review_entry_4_status=reviewed
live_runner_acceptance_denial_review_entry_5_status=met
live_runner_acceptance_denial_review_entry_6_status=recorded
live_runner_acceptance_denial_review_phase_1=load_acceptance_denial_transcript
live_runner_acceptance_denial_review_phase_2=review_closed_gate_denial
live_runner_acceptance_denial_review_phase_3=confirm_no_effect_boundary
live_runner_acceptance_denial_review_phase_4=handoff_to_acceptance_denial_disposition
live_runner_acceptance_denial_review_phase_1_status=contract-only
live_runner_acceptance_denial_review_phase_2_status=review-only
live_runner_acceptance_denial_review_phase_3_status=blocked-no-effect
live_runner_acceptance_denial_review_phase_4_status=future-disposition-only
live_reset_uninstall_runner_present=0
live_reset_uninstall_runner_enabled=0
managed_wrapper_removal_performed=0
managed_app_bundle_removal_performed=0
managed_application_support_removal_performed=0
reset_receipt_write_performed=0
absence_report_run_performed=0
absence_report_written=0
file_delete_performed=0
directory_delete_performed=0
application_support_write_performed=0
receipt_write_performed=0
app_bundle_write_performed=0
cli_wrapper_write_performed=0
shell_profile_mutation_performed=0
host_mutation_performed=0
network_performed=0
root_authority=0
runtime_authority_granted=0
production_installer_ready=0
next_lane=macos-reset-uninstall-live-runner-acceptance-denial-disposition-closeout-audit-review-disposition-contract
REPORT
