#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

fail() {
  printf 'nadia production readiness blocker status: %s\n' "$1" >&2
  exit 1
}

require_file() {
  file="$1"
  [ -f "$file" ] || fail "missing file: $file"
}

require_file docs/status/NADIA_PROTECTIVE_SAFETY_BOUNDARY_STAGE_6_STATUS.md
require_file docs/status/NADIA_AWARENESS_DIALOGUE_CONTRACT_STAGE_15_STATUS.md
require_file docs/status/NADIA_PROMPT_EVALUATION_RESULT_RELEASE_RECEIPT_REVIEW_DISPOSITION_RELEASE_RECEIPT_REVIEW_DISPOSITION_RELEASE_RECEIPT_REVIEW_DISPOSITION_RELEASE_RECEIPT_REVIEW_DISPOSITION_RELEASE_RECEIPT_CONTRACT_STAGE_51_STATUS.md
require_file scripts/test-nadia-command-surface.sh

cat <<'STATUS'
LATTICRA NADIA PRODUCTION READINESS BLOCKER STATUS
status_version=1
status_mode=no-effect-nadia-production-readiness-blocker-status
nadia_production_readiness_blocker_status_present=1
nadia_production_readiness_status_no_effect=1
stage_6_protective_safety_boundary_status_present=1
stage_15_awareness_dialogue_status_present=1
stage_51_release_receipt_status_present=1
nadia_command_surface_status_present=1
nadia_command_surface_audit_present=1
absolute_protective_boundary_required=1
sexual_user_request_authority=0
sexual_content_generation=0
sexual_roleplay_authority=0
sexualized_namesake_or_survivor_content=0
sexual_request_refusal=always
user_override_authority=0
prompt_injection_override_authority=0
policy_bypass_authority=0
manipulation_resistance_required=1
sexual_safety_runtime_enforcement_validated=0
sexual_safety_adversarial_eval_reviewed=0
manipulation_resistance_red_team_reviewed=0
survivor_sensitive_content_reviewed=0
human_rights_awareness_reviewed=0
nadia_initiative_source_snapshot_reviewed=0
source_citation_pack_reviewed=0
awareness_qa_dataset_reviewed=0
offline_model_artifact_present=0
offline_model_license_reviewed=0
offline_model_integrity_verified=0
tokenizer_artifact_runtime_verified=0
model_load_runtime_validated=0
prompt_evaluation_runtime_validated=0
inference_runtime_validated=0
runtime_sandbox_validated=0
tool_authority_runtime_enforced=0
console_interoperability_e2e_validated=0
panel_install_e2e_validated=0
release_receipt_signed=0
release_receipt_reviewed=0
community_awareness_review_ready=0
production_nadia_ready=0
public_release_allowed=0
network_allowed=0
model_download_allowed=0
prompt_evaluated=0
inference_performed=0
model_runtime_invoked=0
tool_execution_performed=0
source_mutation_performed=0
training_performed=0
distillation_performed=0
host_mutation_performed=0
no_effect=1
STATUS
