#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

fail() {
  printf 'production quality blocker ledger: %s\n' "$1" >&2
  exit 1
}

require_file() {
  file="$1"
  [ -f "$file" ] || fail "missing file: $file"
}

require_contains() {
  pattern="$1"
  file="$2"
  grep -Fq -- "$pattern" "$file" ||
    fail "missing required pattern in $file: $pattern"
}

ledger='docs/status/PRODUCTION_QUALITY_BLOCKER_LEDGER.md'
index='docs/status/README.md'
readme='README.md'
prod='docs/PRODUCTION_INSTALLER_READINESS_CONTRACT.md'
nadia='docs/NADIA_OFFLINE_AI_FOUNDATION.md'

for file in "$ledger" "$index" "$readme" "$prod" "$nadia" Makefile
do
  require_file "$file"
done

require_contains 'Status: active blocker ledger' "$ledger"
require_contains 'local_quality_gate_command=make quality' "$ledger"
require_contains 'local_quality_gate_last_observed=pass-2026-05-28' "$ledger"
require_contains 'This is a strong local validation signal. It is not a production-readiness claim.' "$ledger"
require_contains 'production_platform_claim_allowed=0' "$ledger"
require_contains 'production_installer_ready=0' "$ledger"
require_contains 'production_ai_claimed=0' "$ledger"
require_contains 'production_cryptography_claimed=0' "$ledger"
require_contains 'production_enforcement_claimed=0' "$ledger"
require_contains 'fedora_distribution_ready=0' "$ledger"
require_contains 'fedora_approval_claimed=0' "$ledger"
require_contains 'daily_driver_install_ready=0' "$ledger"
require_contains 'immutable_fedora_ready=0' "$ledger"
require_contains 'installer_preflight_guard_present=1' "$ledger"
require_contains 'installer_preflight_blocks_unsupported_targets=1' "$ledger"
require_contains 'installer_preflight_guard_no_effect=1' "$ledger"
require_contains 'installer_install_plan_preview_present=1' "$ledger"
require_contains 'installer_install_plan_preview_no_effect=1' "$ledger"
require_contains 'This closes the guard-presence and preview-presence gaps only.' "$ledger"
require_contains 'artifact_integrity_status_present=1' "$ledger"
require_contains 'installer_artifact_checksum_status_present=1' "$ledger"
require_contains 'installer_artifact_signature_status_present=1' "$ledger"
require_contains 'fixture_manifest_sha256_recorded=1' "$ledger"
require_contains 'release_artifact_present=0' "$ledger"
require_contains 'release_artifact_sha256_recorded=0' "$ledger"
require_contains 'release_artifact_signature_present=0' "$ledger"
require_contains 'release_artifact_signature_verified=0' "$ledger"
require_contains 'installer_public_key_documented=0' "$ledger"
require_contains 'signature_verification_documented=0' "$ledger"
require_contains 'This does not close the production-installer checksum or signature gates.' "$ledger"
require_contains '## Installer Release Artifact Promotion Gate' "$ledger"
require_contains 'release_artifact_promotion_gate_present=1' "$ledger"
require_contains 'release_artifact_promotion_gate_no_effect=1' "$ledger"
require_contains 'release_artifact_promotion_gate_passed=0' "$ledger"
require_contains 'release_artifact_promotion_gate_decision=blocked-missing-tagged-release-artifact' "$ledger"
require_contains 'release_artifact_built_from_tag=0' "$ledger"
require_contains 'release_artifact_reproducible=0' "$ledger"
require_contains 'release_artifact_sha256_recorded=0' "$ledger"
require_contains 'This closes the promotion-gate-presence gap only.' "$ledger"
require_contains '## Installer Release Artifact Staging Directory' "$ledger"
require_contains 'release_artifact_staging_directory_present=1' "$ledger"
require_contains 'release_artifact_staging_directory_path=artifacts/release' "$ledger"
require_contains 'release_artifact_staging_directory_no_effect=1' "$ledger"
require_contains 'release_artifact_candidate_parent_dir_exists=1' "$ledger"
require_contains 'release_artifact_created=0' "$ledger"
require_contains 'source_archive_created=0' "$ledger"
require_contains 'rpm_build_invoked=0' "$ledger"
require_contains 'signature_created=0' "$ledger"
require_contains 'checksum_recorded=0' "$ledger"
require_contains 'release_artifact_evidence_written=0' "$ledger"
require_contains 'release_artifact_evidence_accepted=0' "$ledger"
require_contains 'This closes the staging-directory-presence gap only.' "$ledger"
require_contains '## Installer Release Signing Identity Reference' "$ledger"
require_contains 'release_signing_identity_reference_validator_present=1' "$ledger"
require_contains 'release_signing_identity_reference_mode=no-secret-inspection-reference-validation' "$ledger"
require_contains 'release_signing_identity_reference_no_effect=1' "$ledger"
require_contains 'release_signing_identity_reference_valid=0' "$ledger"
require_contains 'release_signing_identity_reference_present=0' "$ledger"
require_contains 'release_signing_identity_reference_fingerprint_format_valid=0' "$ledger"
require_contains 'release_artifact_signing_identity_reference_present=0' "$ledger"
require_contains 'release_artifact_signing_identity_reference_format_valid=0' "$ledger"
require_contains 'secret_key_inspection_performed=0' "$ledger"
require_contains 'secret_key_material_read=0' "$ledger"
require_contains 'secret_key_material_written=0' "$ledger"
require_contains 'signing_performed=0' "$ledger"
require_contains 'signature_created=0' "$ledger"
require_contains 'signature_verified=0' "$ledger"
require_contains 'This closes the signing-identity-reference-validator presence gap only.' "$ledger"
require_contains '## Installer Release Worktree Cleanliness Audit' "$ledger"
require_contains 'release_worktree_cleanliness_audit_present=1' "$ledger"
require_contains 'release_worktree_cleanliness_audit_mode=no-effect-tracked-status-report' "$ledger"
require_contains 'release_worktree_cleanliness_required_for_release_candidate=1' "$ledger"
require_contains 'release_worktree_cleanliness_audit_passed=0' "$ledger"
require_contains 'release_worktree_tracked_worktree_clean=0' "$ledger"
require_contains 'release_worktree_tracked_dirty_count=<observed>' "$ledger"
require_contains 'release_worktree_dirty_inventory_present=1' "$ledger"
require_contains 'release_worktree_dirty_inventory_mode=stdout-only-tracked-status-list' "$ledger"
require_contains 'release_worktree_dirty_inventory_complete=<observed>' "$ledger"
require_contains 'release_worktree_dirty_inventory_count=<observed>' "$ledger"
require_contains 'release_worktree_dirty_inventory_written=0' "$ledger"
require_contains 'release_worktree_dirty_inventory_accepted=0' "$ledger"
require_contains 'release_worktree_cleanliness_remediation_required=<observed>' "$ledger"
require_contains 'release_artifact_candidate_tracked_dirty_count=<observed>' "$ledger"
require_contains 'git_add_performed=0' "$ledger"
require_contains 'git_commit_performed=0' "$ledger"
require_contains 'git_checkout_performed=0' "$ledger"
require_contains 'git_reset_performed=0' "$ledger"
require_contains 'git_clean_performed=0' "$ledger"
require_contains 'tracked_file_reverted=0' "$ledger"
require_contains 'This closes the worktree-cleanliness-audit and stdout-only dirty-inventory presence gaps only.' "$ledger"
require_contains '## Installer Release Toolchain Availability Audit' "$ledger"
require_contains 'release_toolchain_availability_audit_present=1' "$ledger"
require_contains 'release_toolchain_availability_audit_mode=no-effect-command-visibility-report' "$ledger"
require_contains 'release_toolchain_required_for_release_candidate=1' "$ledger"
require_contains 'release_toolchain_availability_audit_passed=<observed>' "$ledger"
require_contains 'release_toolchain_ready=<observed>' "$ledger"
require_contains 'rpmbuild_available=<observed>' "$ledger"
require_contains 'release_artifact_build_tool_available=<observed>' "$ledger"
require_contains 'rpm_available=<observed>' "$ledger"
require_contains 'release_artifact_query_tool_available=<observed>' "$ledger"
require_contains 'package_manager_invoked=0' "$ledger"
require_contains 'network_allowed=0' "$ledger"
require_contains 'This closes the release-toolchain-availability-audit presence gap only.' "$ledger"
require_contains '## Installer Release Artifact Candidate Preflight' "$ledger"
require_contains 'release_artifact_candidate_preflight_present=1' "$ledger"
require_contains 'release_artifact_candidate_preflight_mode=no-effect-build-signing-readiness' "$ledger"
require_contains 'release_artifact_candidate_preflight_no_effect=1' "$ledger"
require_contains 'release_artifact_candidate_preflight_passed=0' "$ledger"
require_contains 'release_artifact_candidate_inputs_satisfied=0' "$ledger"
require_contains 'release_artifact_candidate_tag_exists=1' "$ledger"
require_contains 'release_artifact_candidate_parent_dir_exists=1' "$ledger"
require_contains 'release_worktree_cleanliness_audit_present=1' "$ledger"
require_contains 'release_worktree_cleanliness_required_for_release_candidate=1' "$ledger"
require_contains 'release_artifact_candidate_tracked_worktree_clean=0' "$ledger"
require_contains 'release_worktree_tracked_worktree_clean=0' "$ledger"
require_contains 'release_worktree_tracked_dirty_count=<observed>' "$ledger"
require_contains 'release_toolchain_availability_audit_present=1' "$ledger"
require_contains 'release_toolchain_required_for_release_candidate=1' "$ledger"
require_contains 'release_toolchain_ready=<observed>' "$ledger"
require_contains 'release_artifact_build_tool_available=<observed>' "$ledger"
require_contains 'release_artifact_query_tool_available=<observed>' "$ledger"
require_contains 'release_artifact_signing_identity_reference_present=0' "$ledger"
require_contains 'release_artifact_signing_identity_reference_format_valid=0' "$ledger"
require_contains 'release_artifact_created=0' "$ledger"
require_contains 'source_archive_created=0' "$ledger"
require_contains 'rpm_build_invoked=0' "$ledger"
require_contains 'signature_created=0' "$ledger"
require_contains 'checksum_recorded=0' "$ledger"
require_contains 'release_artifact_evidence_written=0' "$ledger"
require_contains 'release_artifact_evidence_accepted=0' "$ledger"
require_contains 'This closes the release-artifact candidate preflight presence gap only.' "$ledger"
require_contains '## Installer Release Artifact Evidence Template' "$ledger"
require_contains 'release_artifact_evidence_template_present=1' "$ledger"
require_contains 'release_artifact_evidence_template_mode=no-effect-template' "$ledger"
require_contains 'release_artifact_evidence_template_decision=blocked-template-only-no-evidence-write' "$ledger"
require_contains 'release_artifact_evidence_template_complete=0' "$ledger"
require_contains 'release_artifact_evidence_written_by_template=0' "$ledger"
require_contains 'release_artifact_evidence_accepted_by_template=0' "$ledger"
require_contains 'This closes the release-artifact evidence-template presence gap only.' "$ledger"
require_contains '## Installer Release Artifact Evidence Intake Validator' "$ledger"
require_contains 'release_artifact_evidence_intake_validator_present=1' "$ledger"
require_contains 'release_artifact_evidence_intake_validation_mode=no-effect-validation' "$ledger"
require_contains 'release_artifact_evidence_template_present=1' "$ledger"
require_contains 'release_artifact_evidence_template_complete=0' "$ledger"
require_contains 'release_artifact_candidate_valid=0' "$ledger"
require_contains 'release_artifact_sha256_matches=0' "$ledger"
require_contains 'release_artifact_evidence_accepted_by_intake_validator=0' "$ledger"
require_contains 'release_artifact_evidence_written_by_intake_validator=0' "$ledger"
require_contains 'release_artifact_promotion_allowed_by_intake_validator_alone=0' "$ledger"
require_contains 'This closes the release-artifact evidence-intake-validator presence gap only.' "$ledger"
require_contains '## Installer SBOM Status' "$ledger"
require_contains 'production_installer_sbom_status_present=1' "$ledger"
require_contains 'installer_sbom_status_present=1' "$ledger"
require_contains 'installer_sbom_review_gate_present=1' "$ledger"
require_contains 'installer_sbom_status_no_effect=1' "$ledger"
require_contains 'artifact_manifest_sbom_path=none' "$ledger"
require_contains 'artifact_manifest_sbom_recorded=0' "$ledger"
require_contains 'sbom_artifact_present=0' "$ledger"
require_contains 'sbom_format_declared=0' "$ledger"
require_contains 'sbom_component_inventory_present=0' "$ledger"
require_contains 'sbom_dependency_reviewed=0' "$ledger"
require_contains 'sbom_vulnerability_reviewed=0' "$ledger"
require_contains 'sbom_license_reviewed=0' "$ledger"
require_contains 'sbom_reviewed=0' "$ledger"
require_contains 'This closes the SBOM-status-presence gap only.' "$ledger"
require_contains '## Installer SBOM Evidence Template' "$ledger"
require_contains 'sbom_evidence_template_present=1' "$ledger"
require_contains 'sbom_evidence_template_mode=no-effect-template' "$ledger"
require_contains 'sbom_evidence_template_decision=blocked-template-only-no-evidence-write' "$ledger"
require_contains 'sbom_evidence_template_complete=0' "$ledger"
require_contains 'sbom_generated_by_template=0' "$ledger"
require_contains 'sbom_evidence_written_by_template=0' "$ledger"
require_contains 'sbom_evidence_accepted_by_template=0' "$ledger"
require_contains 'This closes the SBOM evidence-template presence gap only.' "$ledger"
require_contains '## Installer SBOM Evidence Intake Validator' "$ledger"
require_contains 'sbom_evidence_intake_validator_present=1' "$ledger"
require_contains 'sbom_evidence_intake_validation_mode=no-effect-validation' "$ledger"
require_contains 'sbom_evidence_template_present=1' "$ledger"
require_contains 'sbom_evidence_template_complete=0' "$ledger"
require_contains 'sbom_evidence_candidate_valid=0' "$ledger"
require_contains 'sbom_artifact_file_present=0' "$ledger"
require_contains 'sbom_artifact_sha256_recorded=0' "$ledger"
require_contains 'sbom_dependency_review_present=0' "$ledger"
require_contains 'sbom_vulnerability_review_present=0' "$ledger"
require_contains 'sbom_license_review_present=0' "$ledger"
require_contains 'sbom_review_present=0' "$ledger"
require_contains 'sbom_evidence_accepted_by_intake_validator=0' "$ledger"
require_contains 'sbom_evidence_written_by_intake_validator=0' "$ledger"
require_contains 'installer_sbom_promotion_allowed_by_intake_validator_alone=0' "$ledger"
require_contains 'This closes the SBOM evidence-intake-validator presence gap only.' "$ledger"
require_contains '## Installer Transcript Status' "$ledger"
require_contains 'production_installer_transcript_status_present=1' "$ledger"
require_contains 'installer_transcript_status_present=1' "$ledger"
require_contains 'installer_install_transcript_status_present=1' "$ledger"
require_contains 'installer_uninstall_transcript_status_present=1' "$ledger"
require_contains 'installer_post_removal_absence_status_present=1' "$ledger"
require_contains 'installer_transcript_status_no_effect=1' "$ledger"
require_contains 'install_transcript_present=0' "$ledger"
require_contains 'uninstall_transcript_present=0' "$ledger"
require_contains 'post_removal_absence_transcript_present=0' "$ledger"
require_contains 'install_transcript_reviewed=0' "$ledger"
require_contains 'uninstall_transcript_reviewed=0' "$ledger"
require_contains 'post_removal_absence_reviewed=0' "$ledger"
require_contains 'This closes the transcript-status-presence gap only.' "$ledger"
require_contains '## Installer Transcript Evidence Template' "$ledger"
require_contains 'transcript_evidence_template_present=1' "$ledger"
require_contains 'transcript_evidence_template_mode=no-effect-template' "$ledger"
require_contains 'transcript_evidence_template_decision=blocked-template-only-no-evidence-write' "$ledger"
require_contains 'transcript_evidence_template_complete=0' "$ledger"
require_contains 'transcripts_created_by_template=0' "$ledger"
require_contains 'transcript_hashes_calculated_by_template=0' "$ledger"
require_contains 'transcript_evidence_written_by_template=0' "$ledger"
require_contains 'transcript_evidence_accepted_by_template=0' "$ledger"
require_contains 'This closes the transcript evidence-template presence gap only.' "$ledger"
require_contains '## Installer Transcript Evidence Intake Validator' "$ledger"
require_contains 'transcript_evidence_intake_validator_present=1' "$ledger"
require_contains 'transcript_evidence_intake_validation_mode=no-effect-validation' "$ledger"
require_contains 'transcript_evidence_template_present=1' "$ledger"
require_contains 'transcript_evidence_template_complete=0' "$ledger"
require_contains 'transcript_evidence_candidate_valid=0' "$ledger"
require_contains 'install_transcript_file_present=0' "$ledger"
require_contains 'uninstall_transcript_file_present=0' "$ledger"
require_contains 'post_removal_absence_transcript_file_present=0' "$ledger"
require_contains 'install_transcript_sha256_recorded=0' "$ledger"
require_contains 'uninstall_transcript_sha256_recorded=0' "$ledger"
require_contains 'post_removal_absence_transcript_sha256_recorded=0' "$ledger"
require_contains 'install_transcript_review_present=0' "$ledger"
require_contains 'uninstall_transcript_review_present=0' "$ledger"
require_contains 'post_removal_absence_review_present=0' "$ledger"
require_contains 'transcript_evidence_accepted_by_intake_validator=0' "$ledger"
require_contains 'transcript_evidence_written_by_intake_validator=0' "$ledger"
require_contains 'installer_transcript_promotion_allowed_by_intake_validator_alone=0' "$ledger"
require_contains 'This closes the transcript evidence-intake-validator presence gap only.' "$ledger"
require_contains '## Installer Lifecycle Validation Status' "$ledger"
require_contains 'production_installer_lifecycle_validation_status_present=1' "$ledger"
require_contains 'installer_upgrade_status_present=1' "$ledger"
require_contains 'installer_rollback_status_present=1' "$ledger"
require_contains 'installer_reinstall_idempotence_status_present=1' "$ledger"
require_contains 'installer_lifecycle_validation_status_no_effect=1' "$ledger"
require_contains 'installer_upgrade_candidate_present=0' "$ledger"
require_contains 'installer_rollback_candidate_present=0' "$ledger"
require_contains 'installer_reinstall_candidate_present=0' "$ledger"
require_contains 'upgrade_transcript_present=0' "$ledger"
require_contains 'rollback_transcript_present=0' "$ledger"
require_contains 'reinstall_transcript_present=0' "$ledger"
require_contains 'upgrade_transcript_reviewed=0' "$ledger"
require_contains 'rollback_transcript_reviewed=0' "$ledger"
require_contains 'reinstall_transcript_reviewed=0' "$ledger"
require_contains 'installer_downgrade_or_rollback_path_validated=0' "$ledger"
require_contains 'installer_reinstall_idempotence_validated=0' "$ledger"
require_contains 'This closes the lifecycle-status-presence gap only.' "$ledger"
require_contains '## Installer Lifecycle Evidence Intake Validator' "$ledger"
require_contains 'lifecycle_evidence_intake_validator_present=1' "$ledger"
require_contains 'lifecycle_evidence_intake_validation_mode=no-effect-validation' "$ledger"
require_contains 'lifecycle_evidence_candidate_valid=0' "$ledger"
require_contains 'upgrade_transcript_file_present=0' "$ledger"
require_contains 'rollback_transcript_file_present=0' "$ledger"
require_contains 'reinstall_transcript_file_present=0' "$ledger"
require_contains 'upgrade_transcript_sha256_recorded=0' "$ledger"
require_contains 'rollback_transcript_sha256_recorded=0' "$ledger"
require_contains 'reinstall_transcript_sha256_recorded=0' "$ledger"
require_contains 'upgrade_transcript_review_present=0' "$ledger"
require_contains 'rollback_transcript_review_present=0' "$ledger"
require_contains 'reinstall_transcript_review_present=0' "$ledger"
require_contains 'lifecycle_evidence_accepted_by_intake_validator=0' "$ledger"
require_contains 'lifecycle_evidence_written_by_intake_validator=0' "$ledger"
require_contains 'installer_lifecycle_promotion_allowed_by_intake_validator_alone=0' "$ledger"
require_contains 'This closes the lifecycle evidence-intake-validator presence gap only.' "$ledger"
require_contains '## Installer Recovery Failure-Mode Status' "$ledger"
require_contains 'production_installer_recovery_failure_mode_status_present=1' "$ledger"
require_contains 'installer_failure_mode_status_present=1' "$ledger"
require_contains 'installer_recovery_runbook_status_present=1' "$ledger"
require_contains 'installer_recovery_drill_status_present=1' "$ledger"
require_contains 'installer_recovery_failure_mode_status_no_effect=1' "$ledger"
require_contains 'recovery_runbook_present=0' "$ledger"
require_contains 'failure_mode_register_present=0' "$ledger"
require_contains 'recovery_drill_transcript_present=0' "$ledger"
require_contains 'rollback_drill_transcript_present=0' "$ledger"
require_contains 'operator_recovery_receipt_present=0' "$ledger"
require_contains 'recovery_runbook_reviewed=0' "$ledger"
require_contains 'failure_mode_register_reviewed=0' "$ledger"
require_contains 'recovery_drill_reviewed=0' "$ledger"
require_contains 'rollback_drill_reviewed=0' "$ledger"
require_contains 'operator_recovery_receipt_reviewed=0' "$ledger"
require_contains 'installer_failure_mode_documented=0' "$ledger"
require_contains 'installer_recovery_runbook_present=0' "$ledger"
require_contains 'installer_recovery_drill_validated=0' "$ledger"
require_contains 'installer_rollback_drill_validated=0' "$ledger"
require_contains 'installer_failure_mode_evidence_recorded=0' "$ledger"
require_contains 'This closes the recovery-status-presence gap only.' "$ledger"
require_contains '## Installer Recovery Evidence Intake Validator' "$ledger"
require_contains 'recovery_evidence_intake_validator_present=1' "$ledger"
require_contains 'recovery_evidence_intake_validation_mode=no-effect-validation' "$ledger"
require_contains 'recovery_evidence_candidate_valid=0' "$ledger"
require_contains 'recovery_runbook_file_present=0' "$ledger"
require_contains 'failure_mode_register_file_present=0' "$ledger"
require_contains 'recovery_drill_transcript_file_present=0' "$ledger"
require_contains 'rollback_drill_transcript_file_present=0' "$ledger"
require_contains 'operator_recovery_receipt_file_present=0' "$ledger"
require_contains 'recovery_runbook_sha256_recorded=0' "$ledger"
require_contains 'failure_mode_register_sha256_recorded=0' "$ledger"
require_contains 'recovery_drill_transcript_sha256_recorded=0' "$ledger"
require_contains 'rollback_drill_transcript_sha256_recorded=0' "$ledger"
require_contains 'operator_recovery_receipt_sha256_recorded=0' "$ledger"
require_contains 'recovery_runbook_review_present=0' "$ledger"
require_contains 'failure_mode_register_review_present=0' "$ledger"
require_contains 'recovery_drill_review_present=0' "$ledger"
require_contains 'rollback_drill_review_present=0' "$ledger"
require_contains 'operator_recovery_receipt_review_present=0' "$ledger"
require_contains 'recovery_evidence_accepted_by_intake_validator=0' "$ledger"
require_contains 'recovery_evidence_written_by_intake_validator=0' "$ledger"
require_contains 'installer_recovery_promotion_allowed_by_intake_validator_alone=0' "$ledger"
require_contains 'This closes the recovery evidence-intake-validator presence gap only.' "$ledger"
require_contains '## Installer Multi-VM Validation Status' "$ledger"
require_contains 'production_installer_multi_vm_validation_status_present=1' "$ledger"
require_contains 'installer_multi_vm_status_present=1' "$ledger"
require_contains 'installer_fresh_vm_status_present=1' "$ledger"
require_contains 'installer_repeat_vm_status_present=1' "$ledger"
require_contains 'installer_existing_install_status_present=1' "$ledger"
require_contains 'installer_non_root_cli_status_present=1' "$ledger"
require_contains 'installer_root_boundary_status_present=1' "$ledger"
require_contains 'installer_multi_vm_validation_status_no_effect=1' "$ledger"
require_contains 'fresh_vm_validation_evidence_present=0' "$ledger"
require_contains 'repeat_vm_validation_evidence_present=0' "$ledger"
require_contains 'existing_install_validation_evidence_present=0' "$ledger"
require_contains 'remove_reinstall_validation_evidence_present=0' "$ledger"
require_contains 'unsupported_target_validation_evidence_present=0' "$ledger"
require_contains 'non_root_cli_validation_evidence_present=0' "$ledger"
require_contains 'root_boundary_validation_evidence_present=0' "$ledger"
require_contains 'checksum_verification_evidence_present=0' "$ledger"
require_contains 'package_signature_verification_evidence_present=0' "$ledger"
require_contains 'fresh_disposable_fedora_vm_validation=0' "$ledger"
require_contains 'repeat_disposable_fedora_vm_validation=0' "$ledger"
require_contains 'existing_install_upgrade_validation=0' "$ledger"
require_contains 'remove_and_reinstall_validation=0' "$ledger"
require_contains 'unsupported_target_block_validation=0' "$ledger"
require_contains 'non_root_cli_use_validation=0' "$ledger"
require_contains 'root_boundary_validation=0' "$ledger"
require_contains 'checksum_verification_validation=0' "$ledger"
require_contains 'package_signature_verification_validation=0' "$ledger"
require_contains 'installer_fresh_vm_validation_completed=0' "$ledger"
require_contains 'installer_repeat_vm_validation_completed=0' "$ledger"
require_contains 'installer_existing_install_validation_completed=0' "$ledger"
require_contains 'installer_non_root_cli_validation_completed=0' "$ledger"
require_contains 'installer_root_boundary_validation_completed=0' "$ledger"
require_contains 'This closes the multi-VM-status-presence gap only.' "$ledger"
require_contains '## Installer Multi-VM Evidence Intake Validator' "$ledger"
require_contains 'multi_vm_evidence_intake_validator_present=1' "$ledger"
require_contains 'multi_vm_evidence_intake_validation_mode=no-effect-validation' "$ledger"
require_contains 'multi_vm_evidence_candidate_valid=0' "$ledger"
require_contains 'fresh_vm_validation_file_present=0' "$ledger"
require_contains 'repeat_vm_validation_file_present=0' "$ledger"
require_contains 'existing_install_validation_file_present=0' "$ledger"
require_contains 'remove_reinstall_validation_file_present=0' "$ledger"
require_contains 'unsupported_target_validation_file_present=0' "$ledger"
require_contains 'non_root_cli_validation_file_present=0' "$ledger"
require_contains 'root_boundary_validation_file_present=0' "$ledger"
require_contains 'checksum_verification_file_present=0' "$ledger"
require_contains 'package_signature_verification_file_present=0' "$ledger"
require_contains 'fresh_vm_validation_sha256_recorded=0' "$ledger"
require_contains 'repeat_vm_validation_sha256_recorded=0' "$ledger"
require_contains 'existing_install_validation_sha256_recorded=0' "$ledger"
require_contains 'remove_reinstall_validation_sha256_recorded=0' "$ledger"
require_contains 'unsupported_target_validation_sha256_recorded=0' "$ledger"
require_contains 'non_root_cli_validation_sha256_recorded=0' "$ledger"
require_contains 'root_boundary_validation_sha256_recorded=0' "$ledger"
require_contains 'checksum_verification_sha256_recorded=0' "$ledger"
require_contains 'package_signature_verification_sha256_recorded=0' "$ledger"
require_contains 'fresh_vm_validation_review_present=0' "$ledger"
require_contains 'repeat_vm_validation_review_present=0' "$ledger"
require_contains 'existing_install_validation_review_present=0' "$ledger"
require_contains 'remove_reinstall_validation_review_present=0' "$ledger"
require_contains 'unsupported_target_validation_review_present=0' "$ledger"
require_contains 'non_root_cli_validation_review_present=0' "$ledger"
require_contains 'root_boundary_validation_review_present=0' "$ledger"
require_contains 'checksum_verification_review_present=0' "$ledger"
require_contains 'package_signature_verification_review_present=0' "$ledger"
require_contains 'multi_vm_evidence_accepted_by_intake_validator=0' "$ledger"
require_contains 'multi_vm_evidence_written_by_intake_validator=0' "$ledger"
require_contains 'installer_multi_vm_promotion_allowed_by_intake_validator_alone=0' "$ledger"
require_contains 'This closes the multi-VM evidence-intake-validator presence gap only.' "$ledger"
require_contains 'release-artifact worktree cleanliness audit' "$ledger"
require_contains 'release-artifact toolchain availability audit' "$ledger"
require_contains 'release-artifact evidence template' "$ledger"
require_contains 'SBOM evidence template' "$ledger"
require_contains 'multi-VM validation status, and multi-VM evidence intake validator' "$ledger"
require_contains 'clean release worktree' "$ledger"
require_contains 'complete release build/query toolchain' "$ledger"
require_contains 'completed release artifact evidence bundle' "$ledger"
require_contains 'installer_artifact_reproducible=0' "$ledger"
require_contains 'installer_artifact_checksum_recorded=0' "$ledger"
require_contains 'installer_artifact_signature_recorded=0' "$ledger"
require_contains 'installer_sbom_recorded=0' "$ledger"
require_contains 'installer_install_transcript_recorded=0' "$ledger"
require_contains 'installer_uninstall_transcript_recorded=0' "$ledger"
require_contains 'installer_post_removal_absence_verified=0' "$ledger"
require_contains 'installer_upgrade_path_validated=0' "$ledger"
require_contains 'installer_rollback_path_validated=0' "$ledger"
require_contains 'installer_downgrade_or_rollback_path_validated=0' "$ledger"
require_contains 'installer_reinstall_idempotence_validated=0' "$ledger"
require_contains 'installer_failure_mode_documented=0' "$ledger"
require_contains 'installer_recovery_runbook_present=0' "$ledger"
require_contains 'installer_recovery_drill_validated=0' "$ledger"
require_contains 'installer_rollback_drill_validated=0' "$ledger"
require_contains 'installer_failure_mode_evidence_recorded=0' "$ledger"
require_contains 'installer_multi_vm_validation_completed=0' "$ledger"
require_contains 'installer_fresh_vm_validation_completed=0' "$ledger"
require_contains 'installer_repeat_vm_validation_completed=0' "$ledger"
require_contains 'installer_existing_install_validation_completed=0' "$ledger"
require_contains 'installer_non_root_cli_validation_completed=0' "$ledger"
require_contains 'installer_root_boundary_validation_completed=0' "$ledger"
require_contains 'nadia_stage_51_contract_only_foundation_present=1' "$ledger"
require_contains 'nadia_model_runtime_present=0' "$ledger"
require_contains 'nadia_runtime_invoked=0' "$ledger"
require_contains 'nadia_prompt_evaluated=0' "$ledger"
require_contains 'nadia_inference_performed=0' "$ledger"
require_contains 'nadia_dialogue_generated=0' "$ledger"
require_contains 'nadia_tool_execution_authority=0' "$ledger"
require_contains 'nadia_network_authority=0' "$ledger"
require_contains 'nadia_sexual_request_refusal=always' "$ledger"
require_contains 'nadia_manipulation_resistance=required' "$ledger"
require_contains 'Keep the no-effect production-installer preflight guard and preview renderer bound to the Fedora host preflight and local artifact manifest fixture.' "$ledger"
require_contains 'Run the release-artifact worktree cleanliness audit, review the stdout-only tracked dirty inventory, and keep the tracked worktree clean before candidate promotion evidence.' "$ledger"
require_contains 'Run the release-artifact toolchain availability audit in the intended disposable release environment.' "$ledger"
require_contains 'Run the release-artifact candidate preflight against the intended tag, artifact path, and signing identity reference.' "$ledger"
require_contains 'Print the release-artifact evidence template and fill it only from real artifact, checksum, signature, public-key, verification, reproducibility, and review files.' "$ledger"
require_contains 'Create a tagged release artifact candidate and validate its checksum, signature, public-key, verification, reproducibility, and review evidence with the release-artifact evidence intake validator.' "$ledger"
require_contains 'Rerun the promotion gate only after validated release artifact evidence exists.' "$ledger"
require_contains 'Generate and review a production-installer SBOM for the tagged release artifact candidate.' "$ledger"
require_contains 'Print the SBOM evidence template and fill it only from real SBOM, dependency-review, vulnerability-review, license-review, and final-review files.' "$ledger"
require_contains 'Validate the SBOM, dependency review, vulnerability review, license review, and final SBOM review evidence with the SBOM evidence intake validator.' "$ledger"
require_contains 'Run a disposable Fedora VM production-installer dry-run and attach reviewed install, uninstall, and post-removal absence transcript evidence.' "$ledger"
require_contains 'Print the transcript evidence template and fill it only from real install, uninstall, post-removal absence, and review transcript files.' "$ledger"
require_contains 'Validate install, uninstall, post-removal absence, and transcript-review evidence with the transcript evidence intake validator.' "$ledger"
require_contains 'Attach reviewed upgrade, rollback, and reinstall idempotence transcripts from disposable Fedora VM production-installer lifecycle validation.' "$ledger"
require_contains 'Validate upgrade, rollback, reinstall idempotence, and lifecycle-review evidence with the lifecycle evidence intake validator.' "$ledger"
require_contains 'Create and review the production-installer recovery runbook, failure-mode register, recovery drill transcript, rollback drill transcript, and operator recovery receipt.' "$ledger"
require_contains 'Validate recovery runbook, failure-mode register, recovery drill, rollback drill, operator receipt, and review evidence with the recovery evidence intake validator.' "$ledger"
require_contains 'Attach reviewed fresh VM, repeat VM, existing-install upgrade, remove-and-reinstall, unsupported-target block, non-root CLI, root-boundary, checksum verification, and package-signature verification evidence from disposable production-installer validation.' "$ledger"
require_contains 'Validate fresh VM, repeat VM, existing-install upgrade, remove-and-reinstall, unsupported-target block, non-root CLI, root-boundary, checksum verification, package-signature verification, and review evidence with the multi-VM evidence intake validator.' "$ledger"
require_contains 'This ledger is not production readiness.' "$ledger"

require_contains 'PRODUCTION_QUALITY_BLOCKER_LEDGER.md' "$index"
require_contains 'Production quality blocker ledger' "$readme"
require_contains 'installer_preflight_guard_present=1' "$prod"
require_contains 'installer_install_plan_preview_present=1' "$prod"
require_contains 'artifact_integrity_status_present=1' "$prod"
require_contains 'release_artifact_promotion_gate_present=1' "$prod"
require_contains 'release_artifact_promotion_gate_passed=0' "$prod"
require_contains 'release_artifact_staging_directory_present=1' "$prod"
require_contains 'release_artifact_staging_directory_path=artifacts/release' "$prod"
require_contains 'release_artifact_staging_directory_no_effect=1' "$prod"
require_contains 'release_artifact_candidate_preflight_present=1' "$prod"
require_contains 'release_artifact_candidate_preflight_mode=no-effect-build-signing-readiness' "$prod"
require_contains 'release_artifact_candidate_preflight_passed=0' "$prod"
require_contains 'release_artifact_candidate_inputs_satisfied=0' "$prod"
require_contains 'release_artifact_candidate_parent_dir_exists=1' "$prod"
require_contains 'release_worktree_cleanliness_audit_present=1' "$prod"
require_contains 'release_worktree_cleanliness_audit_mode=no-effect-tracked-status-report' "$prod"
require_contains 'release_worktree_cleanliness_required_for_release_candidate=1' "$prod"
require_contains 'release_worktree_cleanliness_audit_passed=0' "$prod"
require_contains 'release_worktree_tracked_worktree_clean=0' "$prod"
require_contains 'release_worktree_tracked_dirty_count=<observed>' "$prod"
require_contains 'release_artifact_candidate_tracked_worktree_clean=0' "$prod"
require_contains 'release_artifact_candidate_tracked_dirty_count=<observed>' "$prod"
require_contains 'release_toolchain_availability_audit_present=1' "$prod"
require_contains 'release_toolchain_availability_audit_mode=no-effect-command-visibility-report' "$prod"
require_contains 'release_toolchain_required_for_release_candidate=1' "$prod"
require_contains 'release_toolchain_availability_audit_passed=<observed>' "$prod"
require_contains 'release_toolchain_ready=<observed>' "$prod"
require_contains 'rpmbuild_available=<observed>' "$prod"
require_contains 'rpm_available=<observed>' "$prod"
require_contains 'release_artifact_build_tool_available=<observed>' "$prod"
require_contains 'release_artifact_query_tool_available=<observed>' "$prod"
require_contains 'release_signing_identity_reference_validator_present=1' "$prod"
require_contains 'release_signing_identity_reference_valid=0' "$prod"
require_contains 'release_signing_identity_reference_fingerprint_format_valid=0' "$prod"
require_contains 'release_artifact_signing_identity_reference_present=0' "$prod"
require_contains 'release_artifact_signing_identity_reference_format_valid=0' "$prod"
require_contains 'secret_key_inspection_performed=0' "$prod"
require_contains 'signing_performed=0' "$prod"
require_contains 'release_artifact_evidence_template_present=1' "$prod"
require_contains 'release_artifact_evidence_template_mode=no-effect-template' "$prod"
require_contains 'release_artifact_evidence_template_complete=0' "$prod"
require_contains 'release_artifact_evidence_written_by_template=0' "$prod"
require_contains 'release_artifact_evidence_accepted_by_template=0' "$prod"
require_contains 'release_artifact_evidence_intake_validator_present=1' "$prod"
require_contains 'production_installer_sbom_status_present=1' "$prod"
require_contains 'installer_sbom_status_present=1' "$prod"
require_contains 'installer_sbom_review_gate_present=1' "$prod"
require_contains 'sbom_evidence_intake_validator_present=1' "$prod"
require_contains 'sbom_evidence_intake_validation_mode=no-effect-validation' "$prod"
require_contains 'sbom_evidence_template_present=1' "$prod"
require_contains 'sbom_evidence_template_mode=no-effect-template' "$prod"
require_contains 'sbom_evidence_template_complete=0' "$prod"
require_contains 'sbom_generated_by_template=0' "$prod"
require_contains 'sbom_evidence_written_by_template=0' "$prod"
require_contains 'sbom_evidence_accepted_by_template=0' "$prod"
require_contains 'sbom_evidence_candidate_valid=0' "$prod"
require_contains 'production_installer_transcript_status_present=1' "$prod"
require_contains 'installer_transcript_status_present=1' "$prod"
require_contains 'installer_install_transcript_status_present=1' "$prod"
require_contains 'transcript_evidence_intake_validator_present=1' "$prod"
require_contains 'transcript_evidence_intake_validation_mode=no-effect-validation' "$prod"
require_contains 'transcript_evidence_template_present=1' "$prod"
require_contains 'transcript_evidence_template_mode=no-effect-template' "$prod"
require_contains 'transcript_evidence_template_complete=0' "$prod"
require_contains 'transcripts_created_by_template=0' "$prod"
require_contains 'transcript_hashes_calculated_by_template=0' "$prod"
require_contains 'transcript_evidence_written_by_template=0' "$prod"
require_contains 'transcript_evidence_accepted_by_template=0' "$prod"
require_contains 'transcript_evidence_candidate_valid=0' "$prod"
require_contains 'production_installer_lifecycle_validation_status_present=1' "$prod"
require_contains 'installer_upgrade_status_present=1' "$prod"
require_contains 'installer_reinstall_idempotence_status_present=1' "$prod"
require_contains 'lifecycle_evidence_intake_validator_present=1' "$prod"
require_contains 'lifecycle_evidence_intake_validation_mode=no-effect-validation' "$prod"
require_contains 'lifecycle_evidence_candidate_valid=0' "$prod"
require_contains 'production_installer_recovery_failure_mode_status_present=1' "$prod"
require_contains 'installer_failure_mode_status_present=1' "$prod"
require_contains 'installer_recovery_runbook_status_present=1' "$prod"
require_contains 'installer_recovery_failure_mode_status_no_effect=1' "$prod"
require_contains 'recovery_evidence_intake_validator_present=1' "$prod"
require_contains 'recovery_evidence_intake_validation_mode=no-effect-validation' "$prod"
require_contains 'recovery_evidence_candidate_valid=0' "$prod"
require_contains 'recovery_evidence_accepted_by_intake_validator=0' "$prod"
require_contains 'recovery_evidence_written_by_intake_validator=0' "$prod"
require_contains 'installer_recovery_promotion_allowed_by_intake_validator_alone=0' "$prod"
require_contains 'production_installer_multi_vm_validation_status_present=1' "$prod"
require_contains 'installer_multi_vm_status_present=1' "$prod"
require_contains 'installer_fresh_vm_status_present=1' "$prod"
require_contains 'installer_multi_vm_validation_status_no_effect=1' "$prod"
require_contains 'multi_vm_evidence_intake_validator_present=1' "$prod"
require_contains 'multi_vm_evidence_intake_validation_mode=no-effect-validation' "$prod"
require_contains 'multi_vm_evidence_candidate_valid=0' "$prod"
require_contains 'multi_vm_evidence_accepted_by_intake_validator=0' "$prod"
require_contains 'multi_vm_evidence_written_by_intake_validator=0' "$prod"
require_contains 'installer_multi_vm_promotion_allowed_by_intake_validator_alone=0' "$prod"
require_contains 'production_installer_ready=0' "$prod"
require_contains 'production_ai_claimed=0' "$nadia"
require_contains 'test-production-quality-blocker-ledger.sh' Makefile

printf 'production_quality_blocker_ledger: ok\n'
