#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

require_file() {
  file="$1"
  if [ ! -f "$file" ]; then
    printf 'production installer readiness contract: missing file: %s\n' "$file" >&2
    exit 1
  fi
}

require_contains() {
  pattern="$1"
  file="$2"
  if ! grep -Fq -- "$pattern" "$file"; then
    printf 'production installer readiness contract: missing required pattern in %s: %s\n' "$file" "$pattern" >&2
    exit 1
  fi
}

doc='docs/PRODUCTION_INSTALLER_READINESS_CONTRACT.md'
readme='README.md'
evidence='docs/status/FEDORA_VM_CLI_PAYLOAD_VALIDATION_EVIDENCE_STATUS.md'

require_file "$doc"
require_file "$readme"
require_file "$evidence"

require_contains 'Status: contract record' "$doc"
require_contains 'Evidence level: 10 target, contract only' "$doc"
require_contains 'before Latticra can claim a production installer' "$doc"
require_contains 'production_installer_ready=0' "$doc"
require_contains 'fedora_distribution_ready=0' "$doc"
require_contains 'fedora_approval_claimed=0' "$doc"
require_contains 'daily_driver_install_ready=0' "$doc"
require_contains 'immutable_fedora_ready=0' "$doc"

require_contains 'disposable_vm_local_rpm_validation_completed=1' "$doc"
require_contains 'disposable_vm_cli_validation_completed=1' "$doc"
require_contains 'host_install_ready_for_cli_payload=1' "$doc"
require_contains '/usr/bin/latticra' "$doc"
require_contains '/usr/share/doc/latticra/README.md' "$doc"

require_contains 'installer_artifact_built_from_tag=1' "$doc"
require_contains 'installer_artifact_reproducible=1' "$doc"
require_contains 'installer_artifact_checksum_recorded=1' "$doc"
require_contains 'installer_artifact_signature_recorded=1' "$doc"
require_contains 'installer_public_key_documented=1' "$doc"
require_contains 'installer_sbom_recorded=1' "$doc"
require_contains 'installer_supported_targets_declared=1' "$doc"
require_contains 'installer_unsupported_targets_declared=1' "$doc"
require_contains 'installer_preflight_guard_present=1' "$doc"
require_contains 'installer_requires_operator_consent=1' "$doc"
require_contains 'installer_install_transcript_recorded=1' "$doc"
require_contains 'installer_uninstall_transcript_recorded=1' "$doc"
require_contains 'installer_post_removal_absence_verified=1' "$doc"
require_contains 'installer_upgrade_path_validated=1' "$doc"
require_contains 'installer_downgrade_or_rollback_path_validated=1' "$doc"
require_contains 'installer_reinstall_idempotence_validated=1' "$doc"
require_contains 'installer_multi_vm_validation_completed=1' "$doc"
require_contains 'installer_security_non_claims_preserved=1' "$doc"

require_contains 'fresh_disposable_fedora_vm_validation=1' "$doc"
require_contains 'repeat_disposable_fedora_vm_validation=1' "$doc"
require_contains 'existing_install_upgrade_validation=1' "$doc"
require_contains 'remove_and_reinstall_validation=1' "$doc"
require_contains 'unsupported_target_block_validation=1' "$doc"
require_contains 'package_signature_verification_validation=1' "$doc"
require_contains 'checksum_verification_validation=1' "$doc"

require_contains 'PRODUCTION INSTALLER READINESS REPORT' "$doc"
require_contains 'production_installer_ready=1' "$doc"
require_contains 'evidence_level=10' "$doc"
require_contains 'Fedora distribution readiness and Fedora approval remain separate claims' "$doc"

require_contains 'production_installer_contract_present=1' "$doc"
require_contains 'artifact_integrity_status_present=1' "$doc"
require_contains 'installer_artifact_checksum_status_present=1' "$doc"
require_contains 'installer_artifact_signature_status_present=1' "$doc"
require_contains 'release_artifact_promotion_gate_present=1' "$doc"
require_contains 'release_artifact_promotion_gate_no_effect=1' "$doc"
require_contains 'release_artifact_promotion_gate_passed=0' "$doc"
require_contains 'release_artifact_promotion_gate_decision=blocked-missing-tagged-release-artifact' "$doc"
require_contains 'release_artifact_candidate_preflight_present=1' "$doc"
require_contains 'release_artifact_candidate_preflight_mode=no-effect-build-signing-readiness' "$doc"
require_contains 'release_artifact_candidate_preflight_passed=0' "$doc"
require_contains 'release_artifact_candidate_inputs_satisfied=0' "$doc"
require_contains 'release_artifact_candidate_tag_exists=<observed>' "$doc"
require_contains 'release_artifact_staging_directory_present=1' "$doc"
require_contains 'release_artifact_staging_directory_path=artifacts/release' "$doc"
require_contains 'release_artifact_staging_directory_no_effect=1' "$doc"
require_contains 'release_artifact_candidate_parent_dir_exists=1' "$doc"
require_contains 'release_worktree_cleanliness_audit_present=1' "$doc"
require_contains 'release_worktree_cleanliness_audit_mode=no-effect-tracked-status-report' "$doc"
require_contains 'release_worktree_cleanliness_required_for_release_candidate=1' "$doc"
require_contains 'release_worktree_cleanliness_audit_passed=0' "$doc"
require_contains 'release_worktree_tracked_worktree_clean=0' "$doc"
require_contains 'release_worktree_tracked_dirty_count=<observed>' "$doc"
require_contains 'release_artifact_candidate_tracked_worktree_clean=0' "$doc"
require_contains 'release_artifact_candidate_tracked_dirty_count=<observed>' "$doc"
require_contains 'release_toolchain_availability_audit_present=1' "$doc"
require_contains 'release_toolchain_availability_audit_mode=no-effect-command-visibility-report' "$doc"
require_contains 'release_toolchain_required_for_release_candidate=1' "$doc"
require_contains 'release_toolchain_availability_audit_passed=0' "$doc"
require_contains 'release_toolchain_ready=0' "$doc"
require_contains 'rpmbuild_available=0' "$doc"
require_contains 'rpm_available=0' "$doc"
require_contains 'release_artifact_build_tool_available=0' "$doc"
require_contains 'release_artifact_query_tool_available=0' "$doc"
require_contains 'release_signing_identity_reference_validator_present=1' "$doc"
require_contains 'release_signing_identity_reference_valid=0' "$doc"
require_contains 'release_signing_identity_reference_fingerprint_format_valid=0' "$doc"
require_contains 'release_artifact_signing_identity_reference_present=0' "$doc"
require_contains 'release_artifact_signing_identity_reference_format_valid=0' "$doc"
require_contains 'secret_key_inspection_performed=0' "$doc"
require_contains 'secret_key_material_read=0' "$doc"
require_contains 'secret_key_material_written=0' "$doc"
require_contains 'signing_performed=0' "$doc"
require_contains 'release_artifact_created=0' "$doc"
require_contains 'source_archive_created=0' "$doc"
require_contains 'rpm_build_invoked=0' "$doc"
require_contains 'signature_created=0' "$doc"
require_contains 'checksum_recorded=0' "$doc"
require_contains 'release_artifact_evidence_written=0' "$doc"
require_contains 'release_artifact_evidence_accepted=0' "$doc"
require_contains 'package_manager_invoked=0' "$doc"
require_contains 'network_allowed=0' "$doc"
require_contains 'git_add_performed=0' "$doc"
require_contains 'git_commit_performed=0' "$doc"
require_contains 'git_checkout_performed=0' "$doc"
require_contains 'git_reset_performed=0' "$doc"
require_contains 'git_clean_performed=0' "$doc"
require_contains 'tracked_file_reverted=0' "$doc"
require_contains 'release_artifact_evidence_template_present=1' "$doc"
require_contains 'release_artifact_evidence_template_mode=no-effect-template' "$doc"
require_contains 'release_artifact_evidence_template_decision=blocked-template-only-no-evidence-write' "$doc"
require_contains 'release_artifact_evidence_template_complete=0' "$doc"
require_contains 'release_artifact_evidence_written_by_template=0' "$doc"
require_contains 'release_artifact_evidence_accepted_by_template=0' "$doc"
require_contains 'release_artifact_evidence_intake_validator_present=1' "$doc"
require_contains 'release_artifact_evidence_intake_validation_mode=no-effect-validation' "$doc"
require_contains 'release_artifact_candidate_valid=0' "$doc"
require_contains 'release_artifact_sha256_matches=0' "$doc"
require_contains 'release_artifact_evidence_accepted_by_intake_validator=0' "$doc"
require_contains 'release_artifact_evidence_written_by_intake_validator=0' "$doc"
require_contains 'release_artifact_promotion_allowed_by_intake_validator_alone=0' "$doc"
require_contains 'release_artifact_present=0' "$doc"
require_contains 'release_artifact_built_from_tag=0' "$doc"
require_contains 'release_artifact_reproducible=0' "$doc"
require_contains 'release_artifact_sha256_recorded=0' "$doc"
require_contains 'release_artifact_signature_present=0' "$doc"
require_contains 'release_artifact_signature_verified=0' "$doc"
require_contains 'production_installer_sbom_status_present=1' "$doc"
require_contains 'installer_sbom_status_present=1' "$doc"
require_contains 'installer_sbom_review_gate_present=1' "$doc"
require_contains 'installer_sbom_status_no_effect=1' "$doc"
require_contains 'sbom_evidence_intake_validator_present=1' "$doc"
require_contains 'sbom_evidence_intake_validation_mode=no-effect-validation' "$doc"
require_contains 'sbom_evidence_template_present=1' "$doc"
require_contains 'sbom_evidence_template_mode=no-effect-template' "$doc"
require_contains 'sbom_evidence_template_complete=0' "$doc"
require_contains 'sbom_generated_by_template=0' "$doc"
require_contains 'sbom_evidence_written_by_template=0' "$doc"
require_contains 'sbom_evidence_accepted_by_template=0' "$doc"
require_contains 'sbom_evidence_candidate_valid=0' "$doc"
require_contains 'sbom_evidence_accepted_by_intake_validator=0' "$doc"
require_contains 'sbom_evidence_written_by_intake_validator=0' "$doc"
require_contains 'installer_sbom_promotion_allowed_by_intake_validator_alone=0' "$doc"
require_contains 'sbom_artifact_present=0' "$doc"
require_contains 'sbom_format_declared=0' "$doc"
require_contains 'sbom_component_inventory_present=0' "$doc"
require_contains 'sbom_dependency_reviewed=0' "$doc"
require_contains 'sbom_vulnerability_reviewed=0' "$doc"
require_contains 'sbom_license_reviewed=0' "$doc"
require_contains 'sbom_reviewed=0' "$doc"
require_contains 'sbom_artifact_file_present=0' "$doc"
require_contains 'sbom_artifact_sha256_recorded=0' "$doc"
require_contains 'sbom_dependency_review_present=0' "$doc"
require_contains 'sbom_vulnerability_review_present=0' "$doc"
require_contains 'sbom_license_review_present=0' "$doc"
require_contains 'sbom_review_present=0' "$doc"
require_contains 'production_installer_transcript_status_present=1' "$doc"
require_contains 'installer_transcript_status_present=1' "$doc"
require_contains 'installer_install_transcript_status_present=1' "$doc"
require_contains 'installer_uninstall_transcript_status_present=1' "$doc"
require_contains 'installer_post_removal_absence_status_present=1' "$doc"
require_contains 'installer_transcript_status_no_effect=1' "$doc"
require_contains 'transcript_evidence_intake_validator_present=1' "$doc"
require_contains 'transcript_evidence_intake_validation_mode=no-effect-validation' "$doc"
require_contains 'transcript_evidence_template_present=1' "$doc"
require_contains 'transcript_evidence_template_mode=no-effect-template' "$doc"
require_contains 'transcript_evidence_template_complete=0' "$doc"
require_contains 'transcripts_created_by_template=0' "$doc"
require_contains 'transcript_hashes_calculated_by_template=0' "$doc"
require_contains 'transcript_evidence_written_by_template=0' "$doc"
require_contains 'transcript_evidence_accepted_by_template=0' "$doc"
require_contains 'transcript_evidence_candidate_valid=0' "$doc"
require_contains 'transcript_evidence_accepted_by_intake_validator=0' "$doc"
require_contains 'transcript_evidence_written_by_intake_validator=0' "$doc"
require_contains 'installer_transcript_promotion_allowed_by_intake_validator_alone=0' "$doc"
require_contains 'install_transcript_present=0' "$doc"
require_contains 'uninstall_transcript_present=0' "$doc"
require_contains 'post_removal_absence_transcript_present=0' "$doc"
require_contains 'install_transcript_reviewed=0' "$doc"
require_contains 'uninstall_transcript_reviewed=0' "$doc"
require_contains 'post_removal_absence_reviewed=0' "$doc"
require_contains 'install_transcript_file_present=0' "$doc"
require_contains 'uninstall_transcript_file_present=0' "$doc"
require_contains 'post_removal_absence_transcript_file_present=0' "$doc"
require_contains 'install_transcript_sha256_recorded=0' "$doc"
require_contains 'uninstall_transcript_sha256_recorded=0' "$doc"
require_contains 'post_removal_absence_transcript_sha256_recorded=0' "$doc"
require_contains 'install_transcript_review_present=0' "$doc"
require_contains 'uninstall_transcript_review_present=0' "$doc"
require_contains 'post_removal_absence_review_present=0' "$doc"
require_contains 'production_installer_lifecycle_validation_status_present=1' "$doc"
require_contains 'installer_upgrade_status_present=1' "$doc"
require_contains 'installer_rollback_status_present=1' "$doc"
require_contains 'installer_reinstall_idempotence_status_present=1' "$doc"
require_contains 'installer_lifecycle_validation_status_no_effect=1' "$doc"
require_contains 'lifecycle_evidence_intake_validator_present=1' "$doc"
require_contains 'lifecycle_evidence_intake_validation_mode=no-effect-validation' "$doc"
require_contains 'lifecycle_evidence_candidate_valid=0' "$doc"
require_contains 'lifecycle_evidence_accepted_by_intake_validator=0' "$doc"
require_contains 'lifecycle_evidence_written_by_intake_validator=0' "$doc"
require_contains 'installer_lifecycle_promotion_allowed_by_intake_validator_alone=0' "$doc"
require_contains 'installer_upgrade_candidate_present=0' "$doc"
require_contains 'installer_rollback_candidate_present=0' "$doc"
require_contains 'installer_reinstall_candidate_present=0' "$doc"
require_contains 'upgrade_transcript_present=0' "$doc"
require_contains 'rollback_transcript_present=0' "$doc"
require_contains 'reinstall_transcript_present=0' "$doc"
require_contains 'upgrade_transcript_reviewed=0' "$doc"
require_contains 'rollback_transcript_reviewed=0' "$doc"
require_contains 'reinstall_transcript_reviewed=0' "$doc"
require_contains 'upgrade_transcript_file_present=0' "$doc"
require_contains 'rollback_transcript_file_present=0' "$doc"
require_contains 'reinstall_transcript_file_present=0' "$doc"
require_contains 'upgrade_transcript_sha256_recorded=0' "$doc"
require_contains 'rollback_transcript_sha256_recorded=0' "$doc"
require_contains 'reinstall_transcript_sha256_recorded=0' "$doc"
require_contains 'upgrade_transcript_review_present=0' "$doc"
require_contains 'rollback_transcript_review_present=0' "$doc"
require_contains 'reinstall_transcript_review_present=0' "$doc"
require_contains 'production_installer_recovery_failure_mode_status_present=1' "$doc"
require_contains 'installer_failure_mode_status_present=1' "$doc"
require_contains 'installer_recovery_runbook_status_present=1' "$doc"
require_contains 'installer_recovery_drill_status_present=1' "$doc"
require_contains 'installer_recovery_failure_mode_status_no_effect=1' "$doc"
require_contains 'recovery_runbook_present=0' "$doc"
require_contains 'failure_mode_register_present=0' "$doc"
require_contains 'recovery_drill_transcript_present=0' "$doc"
require_contains 'rollback_drill_transcript_present=0' "$doc"
require_contains 'operator_recovery_receipt_present=0' "$doc"
require_contains 'recovery_runbook_reviewed=0' "$doc"
require_contains 'failure_mode_register_reviewed=0' "$doc"
require_contains 'recovery_drill_reviewed=0' "$doc"
require_contains 'rollback_drill_reviewed=0' "$doc"
require_contains 'operator_recovery_receipt_reviewed=0' "$doc"
require_contains 'recovery_evidence_intake_validator_present=1' "$doc"
require_contains 'recovery_evidence_intake_validation_mode=no-effect-validation' "$doc"
require_contains 'recovery_evidence_candidate_valid=0' "$doc"
require_contains 'recovery_runbook_file_present=0' "$doc"
require_contains 'failure_mode_register_file_present=0' "$doc"
require_contains 'recovery_drill_transcript_file_present=0' "$doc"
require_contains 'rollback_drill_transcript_file_present=0' "$doc"
require_contains 'operator_recovery_receipt_file_present=0' "$doc"
require_contains 'recovery_runbook_sha256_recorded=0' "$doc"
require_contains 'failure_mode_register_sha256_recorded=0' "$doc"
require_contains 'recovery_drill_transcript_sha256_recorded=0' "$doc"
require_contains 'rollback_drill_transcript_sha256_recorded=0' "$doc"
require_contains 'operator_recovery_receipt_sha256_recorded=0' "$doc"
require_contains 'recovery_runbook_review_present=0' "$doc"
require_contains 'failure_mode_register_review_present=0' "$doc"
require_contains 'recovery_drill_review_present=0' "$doc"
require_contains 'rollback_drill_review_present=0' "$doc"
require_contains 'operator_recovery_receipt_review_present=0' "$doc"
require_contains 'recovery_evidence_accepted_by_intake_validator=0' "$doc"
require_contains 'recovery_evidence_written_by_intake_validator=0' "$doc"
require_contains 'installer_recovery_promotion_allowed_by_intake_validator_alone=0' "$doc"
require_contains 'installer_failure_mode_documented=0' "$doc"
require_contains 'installer_recovery_runbook_present=0' "$doc"
require_contains 'installer_recovery_runbook_reviewed=0' "$doc"
require_contains 'installer_recovery_drill_validated=0' "$doc"
require_contains 'installer_rollback_drill_validated=0' "$doc"
require_contains 'installer_failure_mode_evidence_recorded=0' "$doc"
require_contains 'production_installer_multi_vm_validation_status_present=1' "$doc"
require_contains 'installer_multi_vm_status_present=1' "$doc"
require_contains 'installer_fresh_vm_status_present=1' "$doc"
require_contains 'installer_repeat_vm_status_present=1' "$doc"
require_contains 'installer_existing_install_status_present=1' "$doc"
require_contains 'installer_non_root_cli_status_present=1' "$doc"
require_contains 'installer_root_boundary_status_present=1' "$doc"
require_contains 'installer_multi_vm_validation_status_no_effect=1' "$doc"
require_contains 'fresh_vm_validation_evidence_present=0' "$doc"
require_contains 'repeat_vm_validation_evidence_present=0' "$doc"
require_contains 'existing_install_validation_evidence_present=0' "$doc"
require_contains 'remove_reinstall_validation_evidence_present=0' "$doc"
require_contains 'unsupported_target_validation_evidence_present=0' "$doc"
require_contains 'non_root_cli_validation_evidence_present=0' "$doc"
require_contains 'root_boundary_validation_evidence_present=0' "$doc"
require_contains 'checksum_verification_evidence_present=0' "$doc"
require_contains 'package_signature_verification_evidence_present=0' "$doc"
require_contains 'fresh_vm_validation_reviewed=0' "$doc"
require_contains 'repeat_vm_validation_reviewed=0' "$doc"
require_contains 'existing_install_validation_reviewed=0' "$doc"
require_contains 'remove_reinstall_validation_reviewed=0' "$doc"
require_contains 'unsupported_target_validation_reviewed=0' "$doc"
require_contains 'non_root_cli_validation_reviewed=0' "$doc"
require_contains 'root_boundary_validation_reviewed=0' "$doc"
require_contains 'checksum_verification_reviewed=0' "$doc"
require_contains 'package_signature_verification_reviewed=0' "$doc"
require_contains 'multi_vm_evidence_intake_validator_present=1' "$doc"
require_contains 'multi_vm_evidence_intake_validation_mode=no-effect-validation' "$doc"
require_contains 'multi_vm_evidence_candidate_valid=0' "$doc"
require_contains 'fresh_vm_validation_file_present=0' "$doc"
require_contains 'repeat_vm_validation_file_present=0' "$doc"
require_contains 'existing_install_validation_file_present=0' "$doc"
require_contains 'remove_reinstall_validation_file_present=0' "$doc"
require_contains 'unsupported_target_validation_file_present=0' "$doc"
require_contains 'non_root_cli_validation_file_present=0' "$doc"
require_contains 'root_boundary_validation_file_present=0' "$doc"
require_contains 'checksum_verification_file_present=0' "$doc"
require_contains 'package_signature_verification_file_present=0' "$doc"
require_contains 'fresh_vm_validation_sha256_recorded=0' "$doc"
require_contains 'repeat_vm_validation_sha256_recorded=0' "$doc"
require_contains 'existing_install_validation_sha256_recorded=0' "$doc"
require_contains 'remove_reinstall_validation_sha256_recorded=0' "$doc"
require_contains 'unsupported_target_validation_sha256_recorded=0' "$doc"
require_contains 'non_root_cli_validation_sha256_recorded=0' "$doc"
require_contains 'root_boundary_validation_sha256_recorded=0' "$doc"
require_contains 'checksum_verification_sha256_recorded=0' "$doc"
require_contains 'package_signature_verification_sha256_recorded=0' "$doc"
require_contains 'fresh_vm_validation_review_present=0' "$doc"
require_contains 'repeat_vm_validation_review_present=0' "$doc"
require_contains 'existing_install_validation_review_present=0' "$doc"
require_contains 'remove_reinstall_validation_review_present=0' "$doc"
require_contains 'unsupported_target_validation_review_present=0' "$doc"
require_contains 'non_root_cli_validation_review_present=0' "$doc"
require_contains 'root_boundary_validation_review_present=0' "$doc"
require_contains 'checksum_verification_review_present=0' "$doc"
require_contains 'package_signature_verification_review_present=0' "$doc"
require_contains 'multi_vm_evidence_accepted_by_intake_validator=0' "$doc"
require_contains 'multi_vm_evidence_written_by_intake_validator=0' "$doc"
require_contains 'installer_multi_vm_promotion_allowed_by_intake_validator_alone=0' "$doc"
require_contains 'fresh_disposable_fedora_vm_validation=0' "$doc"
require_contains 'repeat_disposable_fedora_vm_validation=0' "$doc"
require_contains 'root_boundary_validation=0' "$doc"
require_contains 'installer_artifact_reproducible=0' "$doc"
require_contains 'installer_artifact_checksum_recorded=0' "$doc"
require_contains 'installer_artifact_signature_recorded=0' "$doc"
require_contains 'installer_public_key_documented=0' "$doc"
require_contains 'signature_verification_documented=0' "$doc"
require_contains 'installer_sbom_recorded=0' "$doc"
require_contains 'installer_preflight_guard_present=1' "$doc"
require_contains 'installer_preflight_blocks_unsupported_targets=1' "$doc"
require_contains 'installer_preflight_guard_no_effect=1' "$doc"
require_contains 'installer_install_plan_preview_present=1' "$doc"
require_contains 'installer_install_plan_preview_no_effect=1' "$doc"
require_contains 'installer_install_transcript_recorded=0' "$doc"
require_contains 'installer_uninstall_transcript_recorded=0' "$doc"
require_contains 'installer_post_removal_absence_verified=0' "$doc"
require_contains 'installer_upgrade_path_validated=0' "$doc"
require_contains 'installer_rollback_path_validated=0' "$doc"
require_contains 'installer_downgrade_or_rollback_path_validated=0' "$doc"
require_contains 'installer_reinstall_idempotence_validated=0' "$doc"
require_contains 'installer_multi_vm_validation_completed=0' "$doc"
require_contains 'installer_fresh_vm_validation_completed=0' "$doc"
require_contains 'installer_repeat_vm_validation_completed=0' "$doc"
require_contains 'installer_existing_install_validation_completed=0' "$doc"
require_contains 'installer_non_root_cli_validation_completed=0' "$doc"
require_contains 'installer_root_boundary_validation_completed=0' "$doc"

require_contains 'Run the release-artifact candidate preflight against the intended tag, artifact path, and signing identity reference.' "$doc"
require_contains 'Create a tagged release artifact candidate and collect checksum, signature, public-key, verification, reproducibility, and review evidence.' "$doc"
require_contains 'Validate its checksum, signature, public-key, verification, reproducibility, and review evidence with the release-artifact evidence intake validator.' "$doc"
require_contains 'Generate and review a production-installer SBOM for the tagged release artifact candidate.' "$doc"
require_contains 'Validate the SBOM, dependency review, vulnerability review, license review, and final SBOM review evidence with the SBOM evidence intake validator.' "$doc"
require_contains 'Run a disposable Fedora VM production-installer dry-run and attach reviewed install, uninstall, and post-removal absence transcript evidence.' "$doc"
require_contains 'Validate install, uninstall, post-removal absence, and transcript-review evidence with the transcript evidence intake validator.' "$doc"
require_contains 'Attach reviewed upgrade, rollback, and reinstall idempotence transcripts from disposable Fedora VM production-installer lifecycle validation.' "$doc"
require_contains 'Validate upgrade, rollback, reinstall idempotence, and lifecycle-review evidence with the lifecycle evidence intake validator.' "$doc"
require_contains 'Create and review the production-installer recovery runbook, failure-mode register, recovery drill transcript, rollback drill transcript, and operator recovery receipt.' "$doc"
require_contains 'Validate recovery runbook, failure-mode register, recovery drill, rollback drill, operator receipt, and review evidence with the recovery evidence intake validator.' "$doc"
require_contains 'Attach reviewed fresh VM, repeat VM, existing-install upgrade, remove-and-reinstall, unsupported-target block, non-root CLI, root-boundary, checksum verification, and package-signature verification evidence from disposable production-installer validation.' "$doc"
require_contains 'Validate fresh VM, repeat VM, existing-install upgrade, remove-and-reinstall, unsupported-target block, non-root CLI, root-boundary, checksum verification, package-signature verification, and review evidence with the multi-VM evidence intake validator.' "$doc"
require_contains 'Only then consider production_installer_ready=1.' "$doc"

require_contains 'This contract is not a production installer.' "$doc"
require_contains 'It does not build, sign, publish, install, uninstall, upgrade, rollback, or distribute an installer.' "$doc"
require_contains 'not production readiness' "$doc"
require_contains 'not Fedora approval' "$doc"
require_contains 'not Fedora distribution readiness' "$doc"
require_contains 'not daily-driver readiness' "$doc"
require_contains 'not immutable Fedora readiness' "$doc"

require_contains 'production_installer_ready=0' "$readme"
require_contains 'production installer' "$readme"
require_contains 'host_install_ready_for_cli_payload=1' "$evidence"
require_contains 'production_installer_ready=0' "$evidence"

printf 'production_installer_readiness_contract: ok\n'
