#!/usr/bin/env sh
set -eu

require_file() {
  file="$1"
  if [ ! -f "$file" ]; then
    printf 'runtime-boundary-refinement-implementation: missing file: %s\n' "$file" >&2
    exit 1
  fi
}

require_contains() {
  pattern="$1"
  file="$2"
  if ! grep -Fq -- "$pattern" "$file"; then
    printf 'runtime-boundary-refinement-implementation: missing required pattern in %s: %s\n' "$file" "$pattern" >&2
    exit 1
  fi
}

require_file docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_file docs/RUNTIME_BOUNDARY_REFINEMENT_PLAN.md
require_file include/latticra/runtime_boundary.h
require_file src/runtime_boundary.c
require_file tests/runtime_boundary_lat_pipeline_evidence.c
require_file scripts/test-runtime-boundary.sh

require_contains 'Status: runtime boundary refinement implementation with Lat pipeline clause, declaration, module/count, stage-summary, parse-error, semantic-error, downstream-stage-error, span, comment, Lat LIR module-summary, Lat LIR no-effect, and Lat LIR edge-kind evidence' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'no-effect runtime-boundary evidence reporting' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_status' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_parse_error' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_semantic_error' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_model_error' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_lowering_error' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_lir_error' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_last_completed_stage' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_failed_stage' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_no_effect_chain_ok' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_evidence_level' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_module_name' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_declaration_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_model_declaration_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_first_declaration_node_index' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_first_declaration_kind' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_first_transition_source_index' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_first_clause_node_index' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_first_clause_role' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_first_clause_value' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_span_start_line' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_pipeline_comment_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_module_name' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_report_classification' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_shape_kind' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_module_edge_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_binding_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_text_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_no_effect_chain_ok' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_evidence_level' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_no_effect' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_execution_allowed' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_mutation_allowed' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_server_allowed' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_recovery_allowed' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_hardware_allowed' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_contains_edge_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_binds_edge_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_annotates_edge_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_orders_before_edge_count' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'lat_lir_has_transition_source_edges' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'runtime_boundary_reports_lat_pipeline_evidence' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'does not provide runtime behavior' docs/RUNTIME_BOUNDARY_REFINEMENT_IMPLEMENTATION.md
require_contains 'LATTICRA_RUNTIME_BOUNDARY_LAT_PIPELINE_VALIDATE' include/latticra/runtime_boundary.h
require_contains 'const latticra_lat_pipeline_result_t *lat_pipeline' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_status' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_parse_error' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_semantic_error' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_model_error' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_lowering_error' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_lir_error' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_last_completed_stage' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_failed_stage' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_no_effect_chain_ok' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_evidence_level' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_module_name' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_declaration_count' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_model_declaration_count' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_first_declaration_node_index' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_first_declaration_kind' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_first_transition_source_index' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_first_clause_node_index' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_first_clause_role' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_first_clause_value' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_span' include/latticra/runtime_boundary.h
require_contains 'lat_pipeline_comment_count' include/latticra/runtime_boundary.h
require_contains 'lat_lir_module_name' include/latticra/runtime_boundary.h
require_contains 'lat_lir_report_classification' include/latticra/runtime_boundary.h
require_contains 'lat_lir_shape_kind' include/latticra/runtime_boundary.h
require_contains 'lat_lir_module_edge_count' include/latticra/runtime_boundary.h
require_contains 'lat_lir_binding_count' include/latticra/runtime_boundary.h
require_contains 'lat_lir_text_count' include/latticra/runtime_boundary.h
require_contains 'lat_lir_no_effect_chain_ok' include/latticra/runtime_boundary.h
require_contains 'lat_lir_evidence_level' include/latticra/runtime_boundary.h
require_contains 'lat_lir_no_effect' include/latticra/runtime_boundary.h
require_contains 'lat_lir_execution_allowed' include/latticra/runtime_boundary.h
require_contains 'lat_lir_mutation_allowed' include/latticra/runtime_boundary.h
require_contains 'lat_lir_server_allowed' include/latticra/runtime_boundary.h
require_contains 'lat_lir_recovery_allowed' include/latticra/runtime_boundary.h
require_contains 'lat_lir_hardware_allowed' include/latticra/runtime_boundary.h
require_contains 'lat_lir_contains_edge_count' include/latticra/runtime_boundary.h
require_contains 'lat_lir_binds_edge_count' include/latticra/runtime_boundary.h
require_contains 'lat_lir_annotates_edge_count' include/latticra/runtime_boundary.h
require_contains 'lat_lir_orders_before_edge_count' include/latticra/runtime_boundary.h
require_contains 'lat_lir_transition_edge_count' include/latticra/runtime_boundary.h
require_contains 'lat-pipeline-validate' src/runtime_boundary.c
require_contains 'lat_pipeline_status=' src/runtime_boundary.c
require_contains 'lat_pipeline_parse_error=' src/runtime_boundary.c
require_contains 'lat_pipeline_semantic_error=' src/runtime_boundary.c
require_contains 'lat_pipeline_model_error=' src/runtime_boundary.c
require_contains 'lat_pipeline_lowering_error=' src/runtime_boundary.c
require_contains 'lat_pipeline_lir_error=' src/runtime_boundary.c
require_contains 'lat_pipeline_last_completed_stage=' src/runtime_boundary.c
require_contains 'lat_pipeline_failed_stage=' src/runtime_boundary.c
require_contains 'lat_pipeline_no_effect_chain_ok=' src/runtime_boundary.c
require_contains 'lat_pipeline_evidence_level=' src/runtime_boundary.c
require_contains 'lat_pipeline_module_name=' src/runtime_boundary.c
require_contains 'lat_pipeline_declaration_count=' src/runtime_boundary.c
require_contains 'lat_pipeline_model_declaration_count=' src/runtime_boundary.c
require_contains 'lat_pipeline_first_declaration_node_index=' src/runtime_boundary.c
require_contains 'lat_pipeline_first_declaration_kind=' src/runtime_boundary.c
require_contains 'lat_pipeline_first_transition_source_index=' src/runtime_boundary.c
require_contains 'lat_pipeline_first_clause_node_index=' src/runtime_boundary.c
require_contains 'lat_pipeline_first_clause_role=' src/runtime_boundary.c
require_contains 'lat_pipeline_first_clause_value=' src/runtime_boundary.c
require_contains 'lat_pipeline_span_start_line=' src/runtime_boundary.c
require_contains 'lat_pipeline_comment_count=' src/runtime_boundary.c
require_contains 'lat_lir_module_name=' src/runtime_boundary.c
require_contains 'lat_lir_report_classification=' src/runtime_boundary.c
require_contains 'lat_lir_shape_kind=' src/runtime_boundary.c
require_contains 'lat_lir_module_edge_count=' src/runtime_boundary.c
require_contains 'lat_lir_binding_count=' src/runtime_boundary.c
require_contains 'lat_lir_text_count=' src/runtime_boundary.c
require_contains 'lat_lir_no_effect_chain_ok=' src/runtime_boundary.c
require_contains 'lat_lir_evidence_level=' src/runtime_boundary.c
require_contains 'lat_lir_no_effect=' src/runtime_boundary.c
require_contains 'lat_lir_execution_allowed=' src/runtime_boundary.c
require_contains 'lat_lir_mutation_allowed=' src/runtime_boundary.c
require_contains 'lat_lir_server_allowed=' src/runtime_boundary.c
require_contains 'lat_lir_recovery_allowed=' src/runtime_boundary.c
require_contains 'lat_lir_hardware_allowed=' src/runtime_boundary.c
require_contains 'lat_lir_contains_edge_count=' src/runtime_boundary.c
require_contains 'lat_lir_binds_edge_count=' src/runtime_boundary.c
require_contains 'lat_lir_annotates_edge_count=' src/runtime_boundary.c
require_contains 'lat_lir_orders_before_edge_count=' src/runtime_boundary.c
require_contains 'lat_lir_has_transition_source_edges=' src/runtime_boundary.c
require_contains 'runtime_boundary_reports_lat_pipeline_evidence' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'runtime_boundary_denies_parse_failed_lat_pipeline_metadata' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'runtime_boundary_denies_model_failed_lat_pipeline_metadata' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_parse_error=unsupported_block_comment' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_semantic_error=unknown_transition_source' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_model_error=unsupported_clause' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_last_completed_stage=report' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_failed_stage=parse' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_no_effect_chain_ok=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_evidence_level=2' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_module_name=RuntimeEvidenceModule' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_declaration_count=5' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_model_declaration_count=5' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_first_declaration_node_index=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_first_declaration_kind=state' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_first_transition_source_index=0' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_first_clause_node_index=6' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_first_clause_role=field' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_first_clause_value=root' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_span_start_line=2' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_pipeline_comment_count=2' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_module_name=RuntimeEvidenceModule' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_report_classification=materialized' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_shape_kind=lat-module-graph' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_module_edge_count=5' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_binding_count=2' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_text_count=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_no_effect_chain_ok=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_evidence_level=2' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_no_effect=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_execution_allowed=0' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_mutation_allowed=0' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_server_allowed=0' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_recovery_allowed=0' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_hardware_allowed=0' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_contains_edge_count=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_binds_edge_count=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_annotates_edge_count=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'lat_lir_orders_before_edge_count=1' tests/runtime_boundary_lat_pipeline_evidence.c
require_contains 'runtime_boundary_keeps_lat_lir_execution_future_gated' tests/runtime_boundary_lat_pipeline_evidence.c

printf 'runtime_boundary_refinement_implementation: ok\n'
