#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

fail() {
  printf 'production installer multi-VM validation status contract: %s\n' "$1" >&2
  exit 1
}

require_file() {
  file="$1"
  [ -f "$file" ] || fail "missing file: $file"
}

require_contains() {
  pattern="$1"
  file="$2"
  grep -Fq -- "$pattern" "$file" ||
    fail "missing required pattern in $file: $pattern"
}

require_output_contains() {
  pattern="$1"
  output="$2"
  case "$output" in
    *"$pattern"*) ;;
    *) fail "missing required output pattern: $pattern" ;;
  esac
}

doc='docs/PRODUCTION_INSTALLER_MULTI_VM_VALIDATION_STATUS_CONTRACT.md'
status_script='scripts/production-installer-multi-vm-validation-status.sh'
test_script='scripts/test-production-installer-multi-vm-validation-status-contract.sh'
fixture='fixtures/artifact/local-artifact-manifest.txt'
prod='docs/PRODUCTION_INSTALLER_READINESS_CONTRACT.md'
ledger='docs/status/PRODUCTION_QUALITY_BLOCKER_LEDGER.md'
index='docs/status/README.md'
installer_page='docs/installer.html'

for file in "$doc" "$status_script" "$test_script" "$fixture" "$prod" "$ledger" "$index" "$installer_page" Makefile
do
  require_file "$file"
done

require_contains 'Status: no-effect installer multi-VM validation status contract' "$doc"
require_contains 'Evidence level: 10 target, status evidence only' "$doc"
require_contains 'sh scripts/production-installer-multi-vm-validation-status.sh' "$doc"
require_contains 'production_installer_multi_vm_validation_status_present=1' "$doc"
require_contains 'installer_multi_vm_status_present=1' "$doc"
require_contains 'installer_fresh_vm_status_present=1' "$doc"
require_contains 'installer_repeat_vm_status_present=1' "$doc"
require_contains 'installer_existing_install_status_present=1' "$doc"
require_contains 'installer_non_root_cli_status_present=1' "$doc"
require_contains 'installer_root_boundary_status_present=1' "$doc"
require_contains 'installer_multi_vm_validation_status_no_effect=1' "$doc"
require_contains 'fresh_vm_validation_evidence_present=0' "$doc"
require_contains 'repeat_vm_validation_evidence_present=0' "$doc"
require_contains 'existing_install_validation_evidence_present=0' "$doc"
require_contains 'remove_reinstall_validation_evidence_present=0' "$doc"
require_contains 'unsupported_target_validation_evidence_present=0' "$doc"
require_contains 'non_root_cli_validation_evidence_present=0' "$doc"
require_contains 'root_boundary_validation_evidence_present=0' "$doc"
require_contains 'checksum_verification_evidence_present=0' "$doc"
require_contains 'package_signature_verification_evidence_present=0' "$doc"
require_contains 'fresh_vm_validation_reviewed=0' "$doc"
require_contains 'repeat_vm_validation_reviewed=0' "$doc"
require_contains 'existing_install_validation_reviewed=0' "$doc"
require_contains 'remove_reinstall_validation_reviewed=0' "$doc"
require_contains 'unsupported_target_validation_reviewed=0' "$doc"
require_contains 'non_root_cli_validation_reviewed=0' "$doc"
require_contains 'root_boundary_validation_reviewed=0' "$doc"
require_contains 'checksum_verification_reviewed=0' "$doc"
require_contains 'package_signature_verification_reviewed=0' "$doc"
require_contains 'multi_vm_evidence_intake_validator_present=1' "$doc"
require_contains 'multi_vm_evidence_intake_validation_mode=no-effect-validation' "$doc"
require_contains 'multi_vm_evidence_candidate_valid=0' "$doc"
require_contains 'fresh_vm_validation_file_present=0' "$doc"
require_contains 'repeat_vm_validation_file_present=0' "$doc"
require_contains 'existing_install_validation_file_present=0' "$doc"
require_contains 'remove_reinstall_validation_file_present=0' "$doc"
require_contains 'unsupported_target_validation_file_present=0' "$doc"
require_contains 'non_root_cli_validation_file_present=0' "$doc"
require_contains 'root_boundary_validation_file_present=0' "$doc"
require_contains 'checksum_verification_file_present=0' "$doc"
require_contains 'package_signature_verification_file_present=0' "$doc"
require_contains 'fresh_vm_validation_sha256_recorded=0' "$doc"
require_contains 'repeat_vm_validation_sha256_recorded=0' "$doc"
require_contains 'existing_install_validation_sha256_recorded=0' "$doc"
require_contains 'remove_reinstall_validation_sha256_recorded=0' "$doc"
require_contains 'unsupported_target_validation_sha256_recorded=0' "$doc"
require_contains 'non_root_cli_validation_sha256_recorded=0' "$doc"
require_contains 'root_boundary_validation_sha256_recorded=0' "$doc"
require_contains 'checksum_verification_sha256_recorded=0' "$doc"
require_contains 'package_signature_verification_sha256_recorded=0' "$doc"
require_contains 'fresh_vm_validation_review_present=0' "$doc"
require_contains 'repeat_vm_validation_review_present=0' "$doc"
require_contains 'existing_install_validation_review_present=0' "$doc"
require_contains 'remove_reinstall_validation_review_present=0' "$doc"
require_contains 'unsupported_target_validation_review_present=0' "$doc"
require_contains 'non_root_cli_validation_review_present=0' "$doc"
require_contains 'root_boundary_validation_review_present=0' "$doc"
require_contains 'checksum_verification_review_present=0' "$doc"
require_contains 'package_signature_verification_review_present=0' "$doc"
require_contains 'multi_vm_evidence_accepted_by_intake_validator=0' "$doc"
require_contains 'multi_vm_evidence_written_by_intake_validator=0' "$doc"
require_contains 'installer_multi_vm_promotion_allowed_by_intake_validator_alone=0' "$doc"
require_contains 'release_artifact_promotion_gate_passed=0' "$doc"
require_contains 'fresh_disposable_fedora_vm_validation=0' "$doc"
require_contains 'repeat_disposable_fedora_vm_validation=0' "$doc"
require_contains 'existing_install_upgrade_validation=0' "$doc"
require_contains 'remove_and_reinstall_validation=0' "$doc"
require_contains 'unsupported_target_block_validation=0' "$doc"
require_contains 'non_root_cli_use_validation=0' "$doc"
require_contains 'root_boundary_validation=0' "$doc"
require_contains 'checksum_verification_validation=0' "$doc"
require_contains 'package_signature_verification_validation=0' "$doc"
require_contains 'installer_multi_vm_validation_completed=0' "$doc"
require_contains 'installer_fresh_vm_validation_completed=0' "$doc"
require_contains 'installer_repeat_vm_validation_completed=0' "$doc"
require_contains 'installer_existing_install_validation_completed=0' "$doc"
require_contains 'installer_non_root_cli_validation_completed=0' "$doc"
require_contains 'installer_root_boundary_validation_completed=0' "$doc"
require_contains 'package_manager_invoked=0' "$doc"
require_contains 'production_installer_ready=0' "$doc"
require_contains 'It does not run VMs, install, uninstall, upgrade, rollback, invoke a package manager, write transcripts, mutate a host, or validate production installer multi-VM behavior.' "$doc"
require_contains 'installer_multi_vm_validation_completed=1' "$doc"
require_contains 'Attach reviewed fresh VM, repeat VM, existing-install upgrade, remove-and-reinstall, unsupported-target block, non-root CLI, root-boundary, checksum verification, and package-signature verification evidence from disposable production-installer validation.' "$doc"
require_contains 'Validate fresh VM, repeat VM, existing-install upgrade, remove-and-reinstall, unsupported-target block, non-root CLI, root-boundary, checksum verification, package-signature verification, and review evidence with the multi-VM evidence intake validator.' "$doc"
require_contains 'This status record is not a production installer.' "$doc"

require_contains 'artifact_manifest_fixture_present=1' "$fixture"
require_contains 'artifact_manifest_validated=1' "$fixture"

require_contains 'production_installer_multi_vm_validation_status_present=1' "$prod"
require_contains 'installer_multi_vm_status_present=1' "$prod"
require_contains 'installer_fresh_vm_status_present=1' "$prod"
require_contains 'installer_repeat_vm_status_present=1' "$prod"
require_contains 'installer_existing_install_status_present=1' "$prod"
require_contains 'installer_non_root_cli_status_present=1' "$prod"
require_contains 'installer_root_boundary_status_present=1' "$prod"
require_contains 'installer_multi_vm_validation_status_no_effect=1' "$prod"
require_contains 'installer_multi_vm_validation_completed=0' "$prod"
require_contains 'installer_fresh_vm_validation_completed=0' "$prod"
require_contains 'installer_repeat_vm_validation_completed=0' "$prod"
require_contains 'installer_existing_install_validation_completed=0' "$prod"
require_contains 'installer_non_root_cli_validation_completed=0' "$prod"
require_contains 'installer_root_boundary_validation_completed=0' "$prod"
require_contains 'multi_vm_evidence_intake_validator_present=1' "$prod"
require_contains 'multi_vm_evidence_intake_validation_mode=no-effect-validation' "$prod"
require_contains 'multi_vm_evidence_candidate_valid=0' "$prod"
require_contains 'multi_vm_evidence_accepted_by_intake_validator=0' "$prod"
require_contains 'multi_vm_evidence_written_by_intake_validator=0' "$prod"
require_contains 'installer_multi_vm_promotion_allowed_by_intake_validator_alone=0' "$prod"
require_contains 'production_installer_multi_vm_validation_status_present=1' "$ledger"
require_contains 'installer_multi_vm_status_present=1' "$ledger"
require_contains 'installer_fresh_vm_status_present=1' "$ledger"
require_contains 'installer_repeat_vm_status_present=1' "$ledger"
require_contains 'installer_existing_install_status_present=1' "$ledger"
require_contains 'installer_non_root_cli_status_present=1' "$ledger"
require_contains 'installer_root_boundary_status_present=1' "$ledger"
require_contains 'installer_multi_vm_validation_status_no_effect=1' "$ledger"
require_contains 'installer_multi_vm_validation_completed=0' "$ledger"
require_contains 'multi_vm_evidence_intake_validator_present=1' "$ledger"
require_contains 'multi_vm_evidence_candidate_valid=0' "$ledger"
require_contains 'PRODUCTION_INSTALLER_MULTI_VM_VALIDATION_STATUS_CONTRACT.md' "$index"
require_contains 'PRODUCTION_INSTALLER_MULTI_VM_EVIDENCE_INTAKE_VALIDATOR_CONTRACT.md' "$index"
require_contains 'installer_multi_vm_validation_status' "$installer_page"
require_contains 'multi_vm_evidence_intake_validator' "$installer_page"
require_contains 'test-production-installer-multi-vm-validation-status-contract.sh' Makefile

output="$(sh "$status_script")"
require_output_contains 'LATTICRA PRODUCTION INSTALLER MULTI-VM VALIDATION STATUS' "$output"
require_output_contains 'status_mode=no-effect-installer-multi-vm-validation-status' "$output"
require_output_contains 'production_installer_multi_vm_validation_status_present=1' "$output"
require_output_contains 'installer_multi_vm_status_present=1' "$output"
require_output_contains 'installer_fresh_vm_status_present=1' "$output"
require_output_contains 'installer_repeat_vm_status_present=1' "$output"
require_output_contains 'installer_existing_install_status_present=1' "$output"
require_output_contains 'installer_non_root_cli_status_present=1' "$output"
require_output_contains 'installer_root_boundary_status_present=1' "$output"
require_output_contains 'installer_multi_vm_validation_status_no_effect=1' "$output"
require_output_contains 'production_installer_transcript_status_present=1' "$output"
require_output_contains 'production_installer_lifecycle_validation_status_present=1' "$output"
require_output_contains 'production_installer_recovery_failure_mode_status_present=1' "$output"
require_output_contains 'fresh_vm_validation_evidence_path=artifacts/release/latticra-production-installer-fresh-vm-validation.txt' "$output"
require_output_contains 'repeat_vm_validation_evidence_path=artifacts/release/latticra-production-installer-repeat-vm-validation.txt' "$output"
require_output_contains 'existing_install_validation_evidence_path=artifacts/release/latticra-production-installer-existing-install-validation.txt' "$output"
require_output_contains 'remove_reinstall_validation_evidence_path=artifacts/release/latticra-production-installer-remove-reinstall-validation.txt' "$output"
require_output_contains 'unsupported_target_validation_evidence_path=artifacts/release/latticra-production-installer-unsupported-target-validation.txt' "$output"
require_output_contains 'non_root_cli_validation_evidence_path=artifacts/release/latticra-production-installer-non-root-cli-validation.txt' "$output"
require_output_contains 'root_boundary_validation_evidence_path=artifacts/release/latticra-production-installer-root-boundary-validation.txt' "$output"
require_output_contains 'checksum_verification_evidence_path=artifacts/release/latticra-production-installer-checksum-verification.txt' "$output"
require_output_contains 'package_signature_verification_evidence_path=artifacts/release/latticra-production-installer-package-signature-verification.txt' "$output"
require_output_contains 'fresh_vm_validation_evidence_present=0' "$output"
require_output_contains 'repeat_vm_validation_evidence_present=0' "$output"
require_output_contains 'existing_install_validation_evidence_present=0' "$output"
require_output_contains 'remove_reinstall_validation_evidence_present=0' "$output"
require_output_contains 'unsupported_target_validation_evidence_present=0' "$output"
require_output_contains 'non_root_cli_validation_evidence_present=0' "$output"
require_output_contains 'root_boundary_validation_evidence_present=0' "$output"
require_output_contains 'checksum_verification_evidence_present=0' "$output"
require_output_contains 'package_signature_verification_evidence_present=0' "$output"
require_output_contains 'fresh_vm_validation_reviewed=0' "$output"
require_output_contains 'repeat_vm_validation_reviewed=0' "$output"
require_output_contains 'existing_install_validation_reviewed=0' "$output"
require_output_contains 'remove_reinstall_validation_reviewed=0' "$output"
require_output_contains 'unsupported_target_validation_reviewed=0' "$output"
require_output_contains 'non_root_cli_validation_reviewed=0' "$output"
require_output_contains 'root_boundary_validation_reviewed=0' "$output"
require_output_contains 'checksum_verification_reviewed=0' "$output"
require_output_contains 'package_signature_verification_reviewed=0' "$output"
require_output_contains 'multi_vm_evidence_intake_validator_present=1' "$output"
require_output_contains 'multi_vm_evidence_intake_validation_mode=no-effect-validation' "$output"
require_output_contains 'multi_vm_evidence_candidate_valid=0' "$output"
require_output_contains 'fresh_vm_validation_file_present=0' "$output"
require_output_contains 'repeat_vm_validation_file_present=0' "$output"
require_output_contains 'existing_install_validation_file_present=0' "$output"
require_output_contains 'remove_reinstall_validation_file_present=0' "$output"
require_output_contains 'unsupported_target_validation_file_present=0' "$output"
require_output_contains 'non_root_cli_validation_file_present=0' "$output"
require_output_contains 'root_boundary_validation_file_present=0' "$output"
require_output_contains 'checksum_verification_file_present=0' "$output"
require_output_contains 'package_signature_verification_file_present=0' "$output"
require_output_contains 'fresh_vm_validation_sha256_recorded=0' "$output"
require_output_contains 'repeat_vm_validation_sha256_recorded=0' "$output"
require_output_contains 'existing_install_validation_sha256_recorded=0' "$output"
require_output_contains 'remove_reinstall_validation_sha256_recorded=0' "$output"
require_output_contains 'unsupported_target_validation_sha256_recorded=0' "$output"
require_output_contains 'non_root_cli_validation_sha256_recorded=0' "$output"
require_output_contains 'root_boundary_validation_sha256_recorded=0' "$output"
require_output_contains 'checksum_verification_sha256_recorded=0' "$output"
require_output_contains 'package_signature_verification_sha256_recorded=0' "$output"
require_output_contains 'fresh_vm_validation_review_present=0' "$output"
require_output_contains 'repeat_vm_validation_review_present=0' "$output"
require_output_contains 'existing_install_validation_review_present=0' "$output"
require_output_contains 'remove_reinstall_validation_review_present=0' "$output"
require_output_contains 'unsupported_target_validation_review_present=0' "$output"
require_output_contains 'non_root_cli_validation_review_present=0' "$output"
require_output_contains 'root_boundary_validation_review_present=0' "$output"
require_output_contains 'checksum_verification_review_present=0' "$output"
require_output_contains 'package_signature_verification_review_present=0' "$output"
require_output_contains 'multi_vm_evidence_accepted_by_intake_validator=0' "$output"
require_output_contains 'multi_vm_evidence_written_by_intake_validator=0' "$output"
require_output_contains 'installer_multi_vm_promotion_allowed_by_intake_validator_alone=0' "$output"
require_output_contains 'release_artifact_promotion_gate_passed=0' "$output"
require_output_contains 'fresh_disposable_fedora_vm_validation=0' "$output"
require_output_contains 'repeat_disposable_fedora_vm_validation=0' "$output"
require_output_contains 'existing_install_upgrade_validation=0' "$output"
require_output_contains 'remove_and_reinstall_validation=0' "$output"
require_output_contains 'unsupported_target_block_validation=0' "$output"
require_output_contains 'non_root_cli_use_validation=0' "$output"
require_output_contains 'root_boundary_validation=0' "$output"
require_output_contains 'checksum_verification_validation=0' "$output"
require_output_contains 'package_signature_verification_validation=0' "$output"
require_output_contains 'installer_multi_vm_validation_completed=0' "$output"
require_output_contains 'installer_fresh_vm_validation_completed=0' "$output"
require_output_contains 'installer_repeat_vm_validation_completed=0' "$output"
require_output_contains 'installer_existing_install_validation_completed=0' "$output"
require_output_contains 'installer_non_root_cli_validation_completed=0' "$output"
require_output_contains 'installer_root_boundary_validation_completed=0' "$output"
require_output_contains 'vm_invocation_performed=0' "$output"
require_output_contains 'package_manager_invoked=0' "$output"
require_output_contains 'host_mutation_performed=0' "$output"
require_output_contains 'network_allowed=0' "$output"
require_output_contains 'production_installer_ready=0' "$output"

printf 'production_installer_multi_vm_validation_status_contract: ok\n'
