name: Fedora VM RPM Validation Announcement

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fedora-vm-rpm-validation-announcement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Fedora VM RPM validation announcement
        run: sh scripts/test-fedora-vm-rpm-validation-announcement.sh
