name: Lat Pipeline

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lat-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Run Lat pipeline tests
        run: sh scripts/test-lat-pipeline.sh
